### ISSUE TITLE
Unexpected UFDR report.xml structure, item with duplicated track id

### ISSUE THREAD

**Issue by luizedum** [sepinf-inc/IPED#2323] opened 2024-09-24 16:04 UTC
The following message was presented by IPED 4.1.6 during the processing of a UFDR report:

> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 2024-09-19 14:09:53     [MSG]   [engine.datasource.UfedXmlReader$XMLContentHandler]                     Unexpected UFDR report.xml structure, item with duplicated track id fa4e6cd1f288b8a52ddc0be41a3ae475: relatorio_erro.ufdr/data/Root/system/users/0/photo.png.
> Please report this to project developers sending the UFDR report.xml to add proper support for the new structure.
> 
> IPED finished.
> Check the log at C:\IPED-4.1.6\iped-4.1.6\log\IPED-2024-09-19-14-04-42.log

**Comment by lfcnassif** [comment] 2024-09-24 16:41
Could you please try to process UFDR above with the last snapshot?
https://github.com/sepinf-inc/IPED/actions/runs/10710122355

**Comment by lfcnassif** [comment] 2024-10-17 00:08
@luizedum could you please try to reproduce with snapshot above? We don't have your UFDR to test.

**Comment by lfcnassif** [comment] 2024-10-20 17:02
Closing as can't reproduce. Please reopen if you can share the report.xml or ufdr file.

**Closed by lfcnassif** 2024-10-20 17:02 UTC
Labels: need info
