### ISSUE TITLE
Improve PDF rendering quality

### ISSUE THREAD

**Issue by tc-wleite** [sepinf-inc/IPED#1426] opened 2022-11-10 20:51 UTC
Using IPED 4.0.x to view PDFs, I noticed a pretty low rendering quality, compared to 3.18.x and to external viewers.
It seems related to GUI auto scaling, introduced by the upgrade to Java 11.
If I set UI scaling to 1 (instead of "auto"), the rendering result is better.

Font support is also limited (as mentioned in #379).

An example PDF (screenshot of the viewer):
![image](https://user-images.githubusercontent.com/7217001/201202930-277736a2-cc5e-44fe-b67c-1d1e0cf49c28.png)

**Comment by tc-wleite** [comment] 2022-11-10 20:58
While #379 is pending, I propose two minor changes:

- Upgrade IcePDF (font support is much better, and a lot of fixes have been applied).
- Use rendering hints to improve the rendering quality.

Below is the same PDF, with the same zoom level, after the proposed changes.
The barcode (in the top) is rendered correctly and the fonts seem more readable. 

![image](https://user-images.githubusercontent.com/7217001/201204140-171f4326-8faa-4686-884e-73742ccc725d.png)

**Comment by lfcnassif** [comment] 2022-11-11 22:53
Great, thank you @tc-wleite. I didn't know about IcePdf 7.0.0 release. Seems embedded font rendering is now supported in the community version, I will test with some PDFs on Monday which chars used to be rendered as squares. If it works #379 can be closed.

**Comment by tc-wleite** [comment] 2022-11-11 22:56
Hi @lfcnassif! I ran quite a few tests myself and results seem good. 
I have some concerns about the library dependencies.
I will post more details next week.

**Comment by lfcnassif** [comment] 2022-11-12 00:30
If your concerns are related to pdfbox dep intersections (fontbox?) I already have a large PDF corpus to use for parsing regression tests.

**Comment by tc-wleite** [comment] 2022-11-14 13:02
> If your concerns are related to pdfbox dep intersections (fontbox?) I already have a large PDF corpus to use for parsing regression tests.

As you noticed, IcePDF project migrate to GitHub, which I believe is good, as there were no new releases during a long time before this migration.

When I changed IPED's pom.xml files to use the new version (7.0.0), I noticed that new jars come together, some of them already used in our project.
IcePDF dependencies are listed in: 
https://github.com/pcorless/icepdf/wiki/Library-Dependencies

- **imageio-tiff** from **TwelveMonkeys**: we were not using this ImageIO plugin, so I tested with a large set of TIFFs, and processing performance and results were similar. I believe this one is fine.
- **fontbox** from **Apache PDFBox**: it seems to keep the same version we already use (2.0.26), so this one should be fine. I did run some tests with a large sample of PDFs and didn't notice any different behavior comparing to 4.0.6.
- **jbig2-imageio**: this seems to be already in lib folder, right?
- **jai-imageio-jpeg2000**: this one was already used, but as far as I know, its jar was supposed to stay in plugins folder, because of license issues. I am not sure if leaving it in the lib folder would be allowed, so this is my main concern for now.

**Comment by lfcnassif** [comment] 2022-11-14 13:31
> * **imageio-tiff** from **TwelveMonkeys**: we were not using this ImageIO plugin, so I tested with a large set of TIFFs, and processing performance and results were similar. I believe this one is fine.

Not sure why IcePDF included this, since java 11 already comes with TIFF support and their build source and target are java 11.


> * **jbig2-imageio**: this seems to be already in lib folder, right?

Yes!

> * **jai-imageio-jpeg2000**: this one was already used, but as far as I know, its jar was supposed to stay in plugins folder, because of license issues. I am not sure if leaving it in the lib folder would be allowed, so this is my main concern for now.

Yes, the license is (or at least was) incompatible. PDFBox also doesn't distribute it because of license issues. I think IcePDF should have used the `provided` tag in their pom.xml file (if it is used as a service provider and not directly). It's easy to exclude it from our pom.

**Comment by lfcnassif** [comment] 2022-11-14 13:33
> * **fontbox** from **Apache PDFBox**: it seems to keep the same version we already use (2.0.26), so this one should be fine. I did run some tests with a large sample of PDFs and didn't notice any different behavior comparing to 4.0.6.

Great, thank you!

**Comment by lfcnassif** [comment] 2022-11-16 16:23
> I will test with some PDFs on Monday which chars used to be rendered as squares

All PDFs I tested with embedded fonts and wrong inter char spaces now are rendered fine, thank you @tc-wleite!

**Comment by lfcnassif** [comment] 2022-11-16 16:23
Closed by #1429

**Closed by lfcnassif** 2022-11-16 16:23 UTC
Labels: enhancement
