### ISSUE TITLE
Error processing a forensic copy

### ISSUE THREAD

**Issue by igiuseppem** [sepinf-inc/IPED#2240] opened 2024-06-06 17:06 UTC
Good evening.
I acquired an hard disk in E01 format. The original disk is an ext4 format and the operating system seems to be linux. I processed the forensic copy with IPED, but I get an error. Please find attached the log file.

Kind regards
[IPED-2024-06-06-01-12-45.log](https://github.com/user-attachments/files/15661450/IPED-2024-06-06-01-12-45.log)

**Comment by lfcnassif** [comment] 2024-06-06 17:34
Hi @igiuseppem, seems a missing feature from sleuthkit library for some specific ext4 feature. It is not simple to fix. I suggest you to open the image with FTKImager and, if it opens fine, convert it to AD1 format, which should be processed fine by IPED. You may need to create one AD1 per partition, I think creating one AD1 for the whole image is not possible.

**Comment by igiuseppem** [comment] 2024-06-06 17:52
Hi @lfcnassif!
Yes, it opens fine with FTK Imager (in this way I have seen it is an ext4 file system), but when I want to select the menu "Export Logical Image (AD1)", it is grayed.
![ad1](https://github.com/sepinf-inc/IPED/assets/96940535/5684f8de-fd86-49f5-9061-7a93a2c640f2)

**Comment by lfcnassif** [comment] 2024-06-06 19:31
I think you need to right click on each partition with your mouse and create one AD1 for each of them, or just for the partitions of interest.

**Comment by igiuseppem** [comment] 2024-06-06 20:17
When I right click on the partition I want to export in AD1, there is the "Export Disk Image" I already see in the "File" menu. Here I can't export the image in AD1, but in other kind of format (like dd, aff and so on).

**Comment by lfcnassif** [comment] 2024-06-07 01:09
Sorry @igiuseppem, I gave you a wrong procedure, you should right click on the partition root folder, the tree node below the partition, so the create AD1 option will be enabled.

**Comment by lfcnassif** [comment] 2024-06-07 01:11
![image](https://github.com/sepinf-inc/IPED/assets/7276994/5266793b-f8c5-4935-a5be-8c2a3b4dbae7)

**Comment by lfcnassif** [comment] 2024-06-07 01:24
Wait, I just saw your log on the computer, earlier I was only able to read it from my mobile...

There are 1294 "java.io.IOException: Spazio su disco insufficiente" errors in the log coming from your temporary processing folder/disk. So, although there is some ext4 feature not supported by sleuthkit, seems the "Spazio su disco insufficiente" errors are the main cause of your issues. Try to use a bigger temp disk to process this image, the original E01 or the converted AD1 images.

**Comment by lfcnassif** [comment] 2024-06-08 19:59
Hi @igiuseppem, did using a bigger temp disk help?

**Comment by lfcnassif** [comment] 2024-06-15 13:06
Closing as the main issue seems related to temp disk full. The TSK ext4 unsupported feature issue should be reported and addressed in TSK project. If you are still having issues, please reopen.

**Closed by lfcnassif** 2024-06-15 13:06 UTC
Labels: need info

**Comment by igiuseppem** [comment] 2024-06-15 17:09
> Hi @igiuseppem, did using a bigger temp disk help?

Hi @lfcnassif , sorry for the delay in the answer. I have more space on the temp disk right now, but there is another problem. The indexing with IPED now stops abruptely and restarts the computer. I tried it two times and both times I found the PC at the login screen, like it was restarted.

Please find attached one of the new log

[IPED-2024-06-15-09-21-02.log](https://github.com/user-attachments/files/15848761/IPED-2024-06-15-09-21-02.log)

**Comment by lfcnassif** [comment] 2024-06-15 18:17
> Hi @lfcnassif , sorry for the delay in the answer. I have more space on the temp disk right now, but there is another problem. The indexing with IPED now stops abruptely and restarts the computer. I tried it two times and both times I found the PC at the login screen, like it was restarted.
> 
> Please find attached one of the new log
> 
> [IPED-2024-06-15-09-21-02.log](https://github.com/user-attachments/files/15848761/IPED-2024-06-15-09-21-02.log)

Hi @igiuseppem. I took a look at the log and I didn't find any fatal errors. System reboot could be an operating system or hardware failure. Did you notice how was the memory usage? System reboot may also be caused by memory exaustion. If IPED used all system memory (ideally this should be confirmed), I suggest you going to conf/FileSystemConfig.txt->numImageReaders and change it from auto (5 in your case) to 1 or 2. Then resume the processing with --continue.

**Comment by igiuseppem** [comment] 2024-06-17 14:05
> > Hi @lfcnassif , sorry for the delay in the answer. I have more space on the temp disk right now, but there is another problem. The indexing with IPED now stops abruptely and restarts the computer. I tried it two times and both times I found the PC at the login screen, like it was restarted.
> > Please find attached one of the new log
> > [IPED-2024-06-15-09-21-02.log](https://github.com/user-attachments/files/15848761/IPED-2024-06-15-09-21-02.log)
> 
> Hi @igiuseppem. I took a look at the log and I didn't find any fatal errors. System reboot could be an operating system or hardware failure. Did you notice how was the memory usage? System reboot may also be caused by memory exhaustion. If IPED used all system memory (ideally this should be confirmed), I suggest you going to conf/FileSystemConfig.txt->numImageReaders and change it from auto (5 in your case) to 1 or 2. Then resume the processing with --continue.

About the memory usage, I didn't notice it. I'll try what you suggest.

**Comment by igiuseppem** [comment] 2024-06-18 05:28
Hi @lfcnassif.
About 10 hours later (and right now), the usage of the RAM was at 98% / 99%. There is also a crash error window from firefox. The indexing seems to going on.

**Comment by lfcnassif** [comment] 2024-06-18 11:09
Was a *.hprof memory dump generated in the terminal current folder? If yes, could you zip and share it? If not, try to create it running jstack -l pid

**Comment by igiuseppem** [comment] 2024-06-19 08:05
No, there is not a *.hprof memory dump, neither in the main IPED folder, neither in the destination folder. The system is very slow. I will create the dump with the command you wrote, but I would like to stop the indexing, because the time is increasing instead of the decreasing, despite it has about 3000 files to completion. I want to stop it, but I would like to resume later. Can I stop closing only the progress window? I want to try resetting the numImageReaders parameter.

**Comment by lfcnassif** [comment] 2024-06-19 10:48
> No, there is not a *.hprof memory dump, neither in the main IPED folder, neither in the destination folder.

Usually it is created in the current user folder, the folder where your terminal is opened when the IPED command was run.

> Can I stop closing only the progress window?

I suggest pausing the processing, waiting some seconds or minutes, then close the window.

**Comment by igiuseppem** [comment] 2024-06-20 11:19
> Usually it is created in the current user folder, the folder where your terminal is opened when the IPED command was run.
I confirm there is not a memory dump. The problem persists, despite I tried to change the numImageReaders parameter, setting it to 1 and 2. The RAM is always saturated.
I runned jstack -l pid over 4 "java" process. Please find attached the dump. Note that IPED was paused when I runned jstack.

[dump1.txt](https://github.com/user-attachments/files/15912831/dump1.txt)
[dump2.txt](https://github.com/user-attachments/files/15912832/dump2.txt)
[dump3.txt](https://github.com/user-attachments/files/15912833/dump3.txt)
[dump4.txt](https://github.com/user-attachments/files/15912834/dump4.txt)

**Comment by wladimirleite** [comment] 2024-06-20 13:33
Hi @igiuseppem!
Can you post a screenshot of IPED's processing window?
It may be useful to help figuring out what is going on.

**Comment by paulobreim** [comment] 2024-06-20 16:31
hi @igiuseppem ,

One suggestion, try reducing the number of threads in the LocalConfig.txt file, where it is
numThreads = default.
For example, half of the cores that you have available. Should use less memory.

**Comment by wladimirleite** [comment] 2024-06-20 16:50
> One suggestion, try reducing the number of threads in the LocalConfig.txt file, where it is numThreads = default. For example, half of the cores that you have available. Should use less memory.

In general, that is a good suggestion to reduce memory usage. 
However it is not clear (at least to me) if there are memory issues. 

@igiuseppem, when you said RAM usage was very high (99%), you meant total RAM, right? (not JVM's memory usage)
Which processes are using more memory (a screenshot of TaskManager "details" tab, like the one below, should help):
![image](https://github.com/sepinf-inc/IPED/assets/7217001/ad979402-a329-4c16-94a4-bac9f1238f56)

**Comment by lfcnassif** [comment] 2024-06-20 18:14
> However it is not clear (at least to me) if there are memory issues.

Neither to me, that was just a wild guess from me. A screenshot of the processing window, taken together with the thread dumps (jstack -l pid) would help a lot to.know why processing is taking to long.

**Comment by igiuseppem** [comment] 2024-06-23 22:44
> @igiuseppem, when you said RAM usage was very high (99%), you meant total RAM, right? (not JVM's memory usage)
@wladimirleite Yes, the total amount of RAM is 99%, but it happens only when I process this forensic copy. Never had this kind of problem.

>One suggestion, try reducing the number of threads in the LocalConfig.txt file, where it is numThreads = default.
@paulobreim I tried to use only half the total threads. Same result: RAM at 99% in short time, as in the case I used the total amount of threads.


>Neither to me, that was just a wild guess from me. A screenshot of the processing window, taken together with the thread dumps (jstack -l pid) would help a lot to.know why processing is taking to long.

@lfcnassif I have taken pictures (a screenshot was not possible, because the system was too slow and operating system didn't respond) together with the thread dumps. It is a new indexing, beacause I had to stop the previous, as I needed my workstation for other tasks.

![Iped progress](https://github.com/sepinf-inc/IPED/assets/96940535/71ef2f65-5521-49fa-b778-98f5382c3308)
![Processes](https://github.com/sepinf-inc/IPED/assets/96940535/eb7e7479-fa2f-4eba-8390-1e1c076b47d1)
[dump1.txt](https://github.com/user-attachments/files/15946646/dump1.txt)
[dump2.txt](https://github.com/user-attachments/files/15946647/dump2.txt)
[dump3.txt](https://github.com/user-attachments/files/15946648/dump3.txt)
[dump4.txt](https://github.com/user-attachments/files/15946649/dump4.txt)
[dump5.txt](https://github.com/user-attachments/files/15946650/dump5.txt)
[dump6.txt](https://github.com/user-attachments/files/15946651/dump6.txt)
[dump7.txt](https://github.com/user-attachments/files/15946652/dump7.txt)

**Comment by wladimirleite** [comment] 2024-06-23 23:38
Thanks @igiuseppem!
A last request from my side: in the picture you took from the task manager, can you switch to "Detail" view (it is in the general "process" view) and sort by memory (not by CPU)?

**Comment by wladimirleite** [comment] 2024-06-24 00:49
Complementing my previous comment, from the IPED processing window picture, it seems that most of JVM memory was free (6301 of 8098 MB). And the Task Manager shows 98% total RAM used, but java process was only using ~3 GB. Other visible processes are not using much memory. So something else in consuming the memory, possibly external processes started by IPED (e.g. ImageMagick). In the "Detail" window, sorted by memory used, we may see some useful information.

**Comment by igiuseppem** [comment] 2024-06-24 06:30
Hi @wladimirleite.
In the picture you see, the task manager is already sorted by memory (decreasing order). If you need the details, I can take a picture, but I have to restart again the indexing and doing again also the dumps.

**Comment by lfcnassif** [comment] 2024-06-24 16:34
> @lfcnassif I have taken pictures (a screenshot was not possible, because the system was too slow and operating system didn't respond) together with the thread dumps. It is a new indexing, beacause I had to stop the previous, as I needed my workstation for other tasks.

Thanks @igiuseppem, I took a look at the thread dumps, seems to me the processing was not frozen, but just slow because it was running OCR, which is a heavy task, it may take 4s per image and much more for multipage PDs. Wasn't the number of processed files increasing slowly?

I don't see explicit memory issues here, so my initial wild guess about it should be wrong. I don't have tips why your machine was restarting, maybe the Windows event logs could help you to figure it out.

**Comment by lfcnassif** [comment] 2024-06-24 16:37
> So something else in consuming the memory, possibly external processes started by IPED (e.g. ImageMagick)

AFAIK, in the task manager screenshot sent by @igiuseppem, the memory used by all external processes called by IPED should be taken into account in the OpenJDK processes group.

**Comment by igiuseppem** [comment] 2024-06-25 07:31
> > @lfcnassif I have taken pictures (a screenshot was not possible, because the system was too slow and operating system didn't respond) together with the thread dumps. It is a new indexing, beacause I had to stop the previous, as I needed my workstation for other tasks.
> 
> Thanks @igiuseppem, I took a look at the thread dumps, seems to me the processing was not frozen, but just slow because it was running OCR, which is a heavy task, it may take 4s per image and much more for multipage PDFs. Wasn't the number of processed files increasing slowly?
> 
> I don't see explicit memory issues here, so my initial wild guess about it should be wrong. I don't have tips why your machine was restarting, maybe the Windows event logs could help you to figure it out.

Dear @lfcnassif, that was the problem. I disabled OCR and using all threads IPED finished in about 10 hours.

> Wasn't the number of processed files increasing slowly?
Yes, the number of processed files was increasing very very very slowly. IPED stood still processing a file for a long time (maybe more than an hour), when there were around 3000 files left to finish. Now that I was able to finish the decoding, I saw that the files total around 1700000. With the previous indexing activities on this forensic copy, when IPED was stuck on that file, the total number of files was something like 1006989 and the hours per term increased instead of decreasing. The file on which the processing had focused the most (then I had to stop) was one of the "unallocs". The previous times I decoded the forensic copy with IPED, was generated a blue screen. One of these times, the error was related to the graphic card. I guess that it was because it was executing the OCR on that file it was stuck on. Am I right?

**Comment by lfcnassif** [comment] 2024-06-25 10:51
> Dear @lfcnassif, that was the problem. I disabled OCR and using all threads IPED finished in about 10 hours.

If you disabled OCR in IPED "installation" folder and then resumed processing with --continue, that doesn't work, all configurations are initially copied to output folder and loaded from there, you should change configs in output folder so they can take effect.

> The file on which the processing had focused the most (then I had to stop) was one of the "unallocs". (...) I guess that it was because it was executing the OCR on that file it was stuck on. Am I right?

Actually IPED was recovering lots of deleted files from unallocated space files, according to your screenshot and thread dumps. Then it was running OCR on those thousands of recovered files (images and PDFs), so the slowness is expected in this situation.
