### ISSUE TITLE
Fatal error parsing forensic copy - EXCEPTION_IN_PAGE_ERROR (0xc0000006)

### ISSUE THREAD

**Issue by igiuseppem** [sepinf-inc/IPED#1404] opened 2022-10-26 06:06 UTC
Good morning.
After several hours (more than 24) processing a forensic copy, the process interrupted with the following error:
'#
'# A fatal error has been detected by the Java Runtime Environment:
'#
'#  EXCEPTION_IN_PAGE_ERROR (0xc0000006) at pc=0x0000027322c7f530, pid=18932, tid=19480
'#
'# JRE version: OpenJDK Runtime Environment (11.0.13+8) (build 11.0.13+8-LTS)
'# Java VM: OpenJDK 64-Bit Server VM (11.0.13+8-LTS, mixed mode, tiered, compressed oops, g1 gc, windows-amd64)
'# Problematic frame:
'# v  ~StubRoutines::jbyte_disjoint_arraycopy
'#
'# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
'#
'# An error report file with more information is saved as:
'# C:\IPED\target\release\iped-4.1-snapshot\hs_err_pid18932.log
Compiled method (c2) 53025013 35042       4       org.apache.lucene.store.BufferedChecksumIndexInput::readBytes (23 bytes)
 total in heap  [0x000002732d469810,0x000002732d470e00] = 30192
 relocation     [0x000002732d469988,0x000002732d469ba0] = 536
 main code      [0x000002732d469ba0,0x000002732d46e1e0] = 17984
 stub code      [0x000002732d46e1e0,0x000002732d46e250] = 112
 oops           [0x000002732d46e250,0x000002732d46e260] = 16
 metadata       [0x000002732d46e260,0x000002732d46e378] = 280
 scopes data    [0x000002732d46e378,0x000002732d4700e8] = 7536
 scopes pcs     [0x000002732d4700e8,0x000002732d470ba8] = 2752
 dependencies   [0x000002732d470ba8,0x000002732d470bb8] = 16
 handler table  [0x000002732d470bb8,0x000002732d470cd8] = 288
 nul chk table  [0x000002732d470cd8,0x000002732d470e00] = 296
Compiled method (c2) 53025026 18070       4       java.util.zip.CheckedOutputStream::write (23 bytes)
 total in heap  [0x000002732b7a4b10,0x000002732b7a4e18] = 776
 relocation     [0x000002732b7a4c88,0x000002732b7a4ca0] = 24
 main code      [0x000002732b7a4ca0,0x000002732b7a4d60] = 192
 stub code      [0x000002732b7a4d60,0x000002732b7a4d78] = 24
 metadata       [0x000002732b7a4d78,0x000002732b7a4d80] = 8
 scopes data    [0x000002732b7a4d80,0x000002732b7a4da0] = 32
 scopes pcs     [0x000002732b7a4da0,0x000002732b7a4de0] = 64
 dependencies   [0x000002732b7a4de0,0x000002732b7a4de8] = 8
 handler table  [0x000002732b7a4de8,0x000002732b7a4e18] = 48
Could not load hsdis-amd64.dll; library not loadable; PrintAssembly is disabled
'#
'# If you would like to submit a bug report, please visit:
'#   https://bell-sw.com/support
'#

Is there a way to address it?

Looking forward to hearing you
Kind regards

Giuseppe

**Comment by igiuseppem** [comment] 2022-10-26 13:38
Please find attached the full log.

[hs_err_pid18932.log](https://github.com/sepinf-inc/IPED/files/9870003/hs_err_pid18932.log)

**Comment by lfcnassif** [comment] 2022-10-26 14:00
> hs_err_pid18932.log

Thank you. I would also need your LocalConfig.txt file and command line to check where your directories are. If your output or indexTemp are on a network share (this last one should be totally avoided), that could cause this too.

**Comment by lfcnassif** [comment] 2022-10-26 14:06
> iped.app.processing.Main -d F:\Archivio\Archivio.E01 -o F:\Archivio\dati -p forensic

Just found the cmd line in above log, so I just need the LocalConfig.txt

PS: If you want to use the forensic profile, you should use `-profile` option, `-p` is to provide APFS passwords.

**Comment by lfcnassif** [comment] 2022-10-26 14:33
Maybe, one possible workaround would be to enable the slower `useNIOFSDirectory` option inside `conf/IndexTaskConfig.txt`. But if no network shares are involved, I think it could be a hardware issue with your indexTemp or F: disk (I would need the LocalConfig.txt to point which of them).

**Comment by igiuseppem** [comment] 2022-10-26 19:30
F: disk is an external hard drive.
The index temp is on the fixed drive (it's an SSD) of the computer. 
Please find attached the requested config file.
[LocalConfig.txt](https://github.com/sepinf-inc/IPED/files/9873171/LocalConfig.txt)

**Comment by igiuseppem** [comment] 2022-10-26 19:31
> 
> PS: If you want to use the forensic profile, you should use `-profile` option, `-p` is to provide APFS passwords.

Ok, Thank you

**Comment by lfcnassif** [comment] 2022-10-26 22:18
> F: disk is an external hard drive, connected via USB 3.0 to the computer.
> The index temp is on the fixed drive (it's an SSD) of the computer.
> Please find attached the requested config file.
> [LocalConfig.txt](https://github.com/sepinf-inc/IPED/files/9873171/LocalConfig.txt)

Thanks. So perhaps the issue is related with your SSD disk. Could you search for Windows Event Logs for possible hardware issues? Or could run some SSD integrity test to see if the disk is OK?

**Comment by igiuseppem** [comment] 2022-10-30 08:54
You're welcome.
I have run the SSD integrity test and the hard drive is ok. In the meanwhile, I have used IPED on another forensic copy and it worked without errors.

**Comment by lfcnassif** [comment] 2022-10-30 14:11
Thanks for the feedback. So I will close this as can't reproduce. If the crash happens again, please let us know and reopen this.

**Closed by lfcnassif** 2022-10-30 14:11 UTC
Labels: need info

**Comment by igiuseppem** [comment] 2022-11-01 09:40
I confirm that I parsed again the same forensic copy and it was completed without the fatal error. The only things I did were the cleaning of the temp directories, the integrity scan and changing to "false" the "parseUnknownFiles" and "parseCorruptedFiles" options in the "ParsingTaskConfig.txt" file. Don't know exactly if some of these tasks I performed helped.

**Comment by lfcnassif** [comment] 2022-11-02 00:00
Thank you for testing again.

> changing to "false" the "parseUnknownFiles" and "parseCorruptedFiles" options in the "ParsingTaskConfig.txt"

I think they are not related to this. If your hardware is OK, maybe it was some intermitent Operating System issue, since it is related to a native error while reading a memory mapped file in your host, like pagefile.sys.
