### ISSUE TITLE
Destination folder name with spaces

### ISSUE THREAD

**Issue by brunontr** [sepinf-inc/IPED#856] opened 2021-11-30 23:25 UTC
Hello!
I've had this bug trying to process an E01 image file. After reading the error I figured out that it was an issue with my path, that had spaces on some directories. Solved removing them but I thought that maybe you'd like to know.

For some reason, it adds a **"** just after the destination folder, right before \indexador\data\processing_finished

PS C:\IPED> java.exe -jar .\iped-3.18.9\iped.jar -d '\\10.102.50.13\liti\Op. xxx\yyyy zzzz\image.E01.E01' -o 'D:\IPED-Processado\Op. xxx\yyyy zzzz\'
2021-11-30 20:10:56     [ERROR] [gpinf.indexer.IndexFiles]                      Processing Error:
**java.nio.file.InvalidPathException: Illegal char <"> at index 39: D:\IPED-Processado\Op. xxx\yyyy zzzz"\indexador\data\processing_finished**
        at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:1.8.0_291]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:1.8.0_291]
        at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:1.8.0_291]
        at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:1.8.0_291]
        at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:1.8.0_291]
        at java.io.File.toPath(Unknown Source) ~[?:1.8.0_291]
        at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:201) ~[iped-engine-3.18.9.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.startManager(IndexFiles.java:196) [iped.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.execute(IndexFiles.java:249) [iped.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:319) [iped.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_291]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_291]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_291]
        at dpf.sp.gpinf.indexer.util.CustomLoader.run(CustomLoader.java:65) [iped-engine-3.18.9.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:315) [iped.jar:?]

ERROR!!!
Check the log at C:\IPED\iped-3.18.9\log\IPED-2021-11-30-20-10-55.log

**Comment by lfcnassif** [comment] 2021-12-01 00:46
I'm not able to reproduce this with a test command line in power shell like:
`java -jar .\iped-3.18.9\iped.jar -d 'F:\test-p2p1.001' -o 'e:\teste\3.18.9 space'`

Could you provide a complete (without hiding chars) example cmd line to reproduce this? You can replace your secret strings by similar ones, but I need a full example cmd line that shows how to reproduce. Maybe it's a problem with your command.

**Comment by tc-wleite** [comment] 2021-12-01 00:49
I made a quick test here, using several spaces and PowerShell (which I guess you are using, right?), and it worked fine.
I used the exact same output path and it worked too.

Maybe there is an invalid character (not printable?) somewhere, that came from pasting. 
So type the output path to be sure...

**Comment by lfcnassif** [comment] 2021-12-02 13:16
Closing. Please reopen if you can reproduce typing the command like @tc-wleite said and if you can provide a full example command line to reproduce this.

**Closed by lfcnassif** 2021-12-02 13:16 UTC
Labels: can't reproduce
