### ISSUE TITLE
JBIG2 images in PDFs not being rendered in preview

### ISSUE THREAD

**Issue by milcent** [sepinf-inc/IPED#389] opened 2021-03-12 13:56 UTC
After processing a bunch of pdf files, all non-searchable that had to go through OCR, I noticed that some of them did not show in the preview window.
The OCR-extracted text from these files does appear in the text tab and is searchable when filtering by specific terms. 
The files that did not appear were really small (20 Kb, 50 Kb), probably due to a very low resolution during scanning, but I am not sure if this has anything to do with the problem.
Thanks in advance and congratulations on the great work!

**Comment by lfcnassif** [comment] 2021-03-12 17:18
What IPED version are you using?
What OS?
Are you able to provide a sample file to reproduce?
Could you send the IPEDSearchApp.log?

**Comment by milcent** [comment] 2021-03-12 17:29
I am using IPED 3.18.4 on Windows 10.
I tested with version 3.15.6 too, with the same issue.
Unfortunately, I cannot provide a sample, since it belongs to an ongoing investigation.

**Comment by tc-wleite** [comment] 2021-03-12 17:39
@milcent, do these files open externally (using a double click)?

**Comment by milcent** [comment] 2021-03-12 17:41
They did open with a double-click in my machine, but not in a colleague's with windows 10 Home (mine is Pro).

**Comment by tc-wleite** [comment] 2021-03-12 17:44
I see... I asked that because it could be possible that malformed/corrupted PDF files are not handled by IPED's internal viewer, but the OCR could extract part of their text.

**Comment by lfcnassif** [comment] 2021-03-12 21:21
@milcent sent some samples to me privately, will take a look next week. Possibly IcePDF lib problem too.

**Comment by lfcnassif** [comment] 2021-03-12 21:22
@milcent and about the log?

**Comment by milcent** [comment] 2021-03-12 21:24
The log file is in the .zip too.

Em sex., 12 de mar. de 2021 às 18:22, Luis Nassif ***@***.***>
escreveu:

**Comment by lfcnassif** [comment] 2021-03-15 14:54
I reproduced the issue with samples sent by @milcent, thanks. It is something related to jbig2 images. Strangely they are decoded when OCRing by IcePDF lib, but are not in the IcePDFViewer. I checked and jbig2-imageio-3.0.2.jar library is on classpath of the analysis app.

Also tested the viewer before the refactoring done by @tc-wleite on #55 and the issue was already there. I tested the new PDFBoxViewer described on #379 and it worked. After that, I removed jbig2 lib from classpath and PDFBoxViewer stopped working, so seems jbig2 lib is correctly on classpath of the analysis app.

Finally I tested IcePDF standalone viewer app and when adding jbig2 lib to classpath, it worked.

Still don't know what is happening...

**Comment by milcent** [comment] 2021-03-15 14:59
Thanks for the effort!!
Anyway, the OCR stills works its rendered text is cross-searchable, and it seems this happens with a specific, low-resolution type of pdf file.

**Comment by lfcnassif** [comment] 2021-03-15 17:40
I've found the cause, it is related to Iped custom class loader (CustomURLClassLoader), when disabled, jbig2 lib is found without problems. But that class loader is needed to enabled the OfficeViewer, still need to figure out a solution...

**Comment by lfcnassif** [comment] 2021-03-15 22:14
Spent hours here... Found a possible bug in jbig2 library:
https://issues.apache.org/jira/browse/PDFBOX-4671?focusedCommentId=17302061&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17302061

**Comment by lfcnassif** [comment] 2021-03-16 13:55
They accepted my solution on upstream project. When pdfbox-jbig2-3.0.4 is released, will upgrade and this will be fixed.

**Comment by milcent** [comment] 2021-03-16 15:07
Well, I didn't expect this to go this far, but I'm really happy you found the cause and the fellows at Apache accepted it so fast!
Great job!!

**Comment by lfcnassif** [comment] 2021-03-17 12:52
In the meanwhile, you can uncompress and replace the attached file in [case]/indexador/lib folder to workaround the issue.

[jbig2-imageio-3.0.2.jar.zip](https://github.com/sepinf-inc/IPED/files/6156479/jbig2-imageio-3.0.2.jar.zip)

**Comment by milcent** [comment] 2021-03-17 13:13
WoW! Thank you very much!! It worked beautifully!!

**Comment by lfcnassif** [comment] 2021-03-17 14:03
will close when fixed in code

**Closed** 2021-03-24 23:23 UTC
Labels: bug
