### ISSUE TITLE
Optimize time to generate report when OCR was enabled

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1117] opened 2022-05-17 18:12 UTC
I'm working in that case with 44M items.
When I tried to generate the report (with ~500k items), it is taking too long time. The estimated time is about 50 hours.
The weird thing is that almost all workers are idle. At most two works are occupied.

![image](https://user-images.githubusercontent.com/2973359/168881680-1711b7c1-e770-4974-922b-6ddd7dbbc9a7.png)

**Comment by aberenguel** [comment] 2022-05-17 18:20
[dump.txt](https://github.com/sepinf-inc/IPED/files/8710636/dump.txt)

**Comment by lfcnassif** [comment] 2022-05-17 18:30
> dump.txt

I think the item producer item thread is very slow here:
```
"Thread-51" #145 prio=5 os_prio=0 cpu=887353.50ms elapsed=1046.44s tid=0x00007fa7560ce800 nid=0x2519e7 runnable  [0x00007fa6992fe000]
   java.lang.Thread.State: RUNNABLE
	at org.sqlite.core.NativeDB.step(Native Method)
	- locked <0x00000002c43b4610> (a org.sqlite.core.NativeDB)
	at org.sqlite.core.DB.execute(DB.java:851)
	- locked <0x00000002c43b4610> (a org.sqlite.core.NativeDB)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
	at dpf.sp.gpinf.indexer.parsers.OCRParser.copyOcrResults(OCRParser.java:482)
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.insertIntoProcessQueue(IPEDReader.java:596)
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.processBookmark(IPEDReader.java:213)
	at dpf.sp.gpinf.indexer.datasource.IPEDReader.read(IPEDReader.java:145)
	at dpf.sp.gpinf.indexer.datasource.ItemProducer.run(ItemProducer.java:123)

   Locked ownable synchronizers:
	- None
```
That maybe could be optimized changing OCRParser.storeOcrTextInDb(...) to setAutoCommit mode off in the used sqlite connections and to commit the writes from time to time

**Comment by lfcnassif** [comment] 2022-05-17 18:55
Please take a few other thread dumps to confirm my theory, since the one you sent is in a sqlite read, but maybe that was by randomness. If others are in *.executeUpdate() after OCRParser.storeOcrTextInDb(), that would be a good confirmation.

**Comment by aberenguel** [comment] 2022-05-17 19:07
Every dump I take get the executeQuery trace

```sh
$ jstack -l 2430591 | grep -i execute
        at dpf.sp.gpinf.indexer.Main.execute(Main.java:211)
        at org.sqlite.core.DB.execute(DB.java:851)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
$ jstack -l 2430591 | grep -i execute
        at dpf.sp.gpinf.indexer.Main.execute(Main.java:211)
        at org.sqlite.core.DB.execute(DB.java:851)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
$ jstack -l 2430591 | grep -i execute
        at dpf.sp.gpinf.indexer.Main.execute(Main.java:211)
        at org.sqlite.core.DB.execute(DB.java:851)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
$ jstack -l 2430591 | grep -i execute
        at dpf.sp.gpinf.indexer.Main.execute(Main.java:211)
        at org.sqlite.core.DB.execute(DB.java:851)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
$ jstack -l 2430591 | grep -i execute
        at dpf.sp.gpinf.indexer.Main.execute(Main.java:211)
        at org.sqlite.core.DB.execute(DB.java:851)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
        at org.sqlite.core.DB.execute(DB.java:851)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
$ jstack -l 2430591 | grep -i execute
        at dpf.sp.gpinf.indexer.Main.execute(Main.java:211)
        at org.sqlite.core.DB.execute(DB.java:851)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
$ jstack -l 2430591 | grep -i execute
        at dpf.sp.gpinf.indexer.Main.execute(Main.java:211)
        at org.sqlite.core.DB.execute(DB.java:851)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
```

**Comment by lfcnassif** [comment] 2022-05-17 19:11
I think it should be better to grep -i OCRParser

**Comment by aberenguel** [comment] 2022-05-17 19:13
```sh
$ date && jstack -l 2430591 | grep -i ocr -C 2
ter 17 mai 2022 16:11:54 -03
        - locked <0x00000002c43b4610> (a org.sqlite.core.NativeDB)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
        at dpf.sp.gpinf.indexer.parsers.OCRParser.copyOcrResults(OCRParser.java:482)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.insertIntoProcessQueue(IPEDReader.java:596)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.processBookmark(IPEDReader.java:213)
$ date && jstack -l 2430591 | grep -i ocr -C 2
ter 17 mai 2022 16:12:00 -03
        - locked <0x00000002c43b4610> (a org.sqlite.core.NativeDB)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
        at dpf.sp.gpinf.indexer.parsers.OCRParser.copyOcrResults(OCRParser.java:482)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.insertIntoProcessQueue(IPEDReader.java:596)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.processBookmark(IPEDReader.java:213)
$ date && jstack -l 2430591 | grep -i ocr -C 2
ter 17 mai 2022 16:12:06 -03
        - locked <0x00000002c43b4610> (a org.sqlite.core.NativeDB)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
        at dpf.sp.gpinf.indexer.parsers.OCRParser.copyOcrResults(OCRParser.java:482)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.insertIntoProcessQueue(IPEDReader.java:596)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.processBookmark(IPEDReader.java:213)
$ date && jstack -l 2430591 | grep -i ocr -C 2
ter 17 mai 2022 16:12:14 -03
        - locked <0x00000002c43b4610> (a org.sqlite.core.NativeDB)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
        at dpf.sp.gpinf.indexer.parsers.OCRParser.copyOcrResults(OCRParser.java:482)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.insertIntoProcessQueue(IPEDReader.java:596)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.processBookmark(IPEDReader.java:213)
$ date && jstack -l 2430591 | grep -i ocr -C 2
ter 17 mai 2022 16:12:26 -03
        - locked <0x00000002c43b4610> (a org.sqlite.core.NativeDB)
        at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:77)
        at dpf.sp.gpinf.indexer.parsers.OCRParser.copyOcrResults(OCRParser.java:482)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.insertIntoProcessQueue(IPEDReader.java:596)
        at dpf.sp.gpinf.indexer.datasource.IPEDReader.processBookmark(IPEDReader.java:213)
```

**Comment by lfcnassif** [comment] 2022-05-17 19:15
Thanks, I think that may be optimized too setting autoCommit = false, or by making batch queries for x hashes...

**Comment by lfcnassif** [comment] 2022-05-17 19:19
or maybe that is caused by the LIKE in the query:
`SELECT id, text FROM ocr WHERE id LIKE ?;`

That is used to get results of OCRed images embedded in Documents that were not expanded, e.g. hash1-child0, hash1-child1, hash1-child2...

**Comment by aberenguel** [comment] 2022-05-17 19:38
As the slow query is a SELECT, I think autoCommit = false could not be effective.

I tested the query directly:
```
Execução finalizada sem erros.
Resultado: 0 linhas retornadas em 1536 ms
Na linha 1:
SELECT id, text FROM ocr WHERE id LIKE 'asdasdasd%'
```

**Comment by aberenguel** [comment] 2022-05-17 19:39
The `ocr-results.db` has 1.3GB

**Comment by lfcnassif** [comment] 2022-05-17 20:11
> Resultado: 0 linhas retornadas em 1536 ms

That is interesting, since this is done for every file before it is put in the pipeline. And if you search for an exact match, how long does it take?

**Comment by aberenguel** [comment] 2022-05-17 20:23
```
Execução finalizada sem erros.
Resultado: 1 linhas retornadas em 107 ms
Na linha 1:
SELECT id, text FROM ocr WHERE id LIKE '17407C1383410F8D233BF13F409550B6%'
```
```
Execução finalizada sem erros.
Resultado: 1 linhas retornadas em 4 ms
Na linha 1:
SELECT id, text FROM ocr WHERE id = '17407C1383410F8D233BF13F409550B6'
```

**Comment by lfcnassif** [comment] 2022-05-17 20:48
Maybe that column could be broken into two, but this would be backwards incompatible...
Or maybe the logic could be changed, making the OCRParser (or ParsingTask) to search for OCRed texts in ocr-results.db of original case, instead of copying the results to final report ocr-results.db from producer thread...

**Comment by aberenguel** [comment] 2022-05-17 20:57
As the OCR results were not important in that case, I truncated the table and restarted the report generation.
Now all thread are occupied.

**Comment by aberenguel** [comment] 2022-05-17 20:59
> Maybe that column could be broken into two, but this would be backwards incompatible... 

@tc-wleite suggested this approach talking to me. Is it a problem to be backwards incompatible since the version 4 was not released yet?

> Or maybe the logic could be changed, making the OCRParser (or ParsingTask) to search for OCRed texts in ocr-results.db of original case, instead of copying the results to final report ocr-results.db from producer thread...

In this case, will the `ocr-results.db` be copied to report?

**Comment by lfcnassif** [comment] 2022-05-17 21:06
> @tc-wleite suggested this approach talking to me. Is it a problem to be backwards incompatible since the version 4 was not released yet?

Not a problem, just for your report generation, but I wouldn't like to put more things in the road, if possible...

> In this case, will the `ocr-results.db` be copied to report?

Yes, so searches for OCRed texts could work in the portable case report. I "think" in the past, the whole file used to be copied at once, since it is based on hashes, not IDs, but this bloats the report with OCRed texts of items not included in the report.

**Comment by hauck-jvsh** [comment] 2022-05-18 12:46
I think this may worth a try https://stackoverflow.com/questions/8584499/sqlite-should-like-searchstr-use-an-index/8586390#8586390

**Comment by lfcnassif** [comment] 2022-05-18 13:03
> I think this may worth a try https://stackoverflow.com/questions/8584499/sqlite-should-like-searchstr-use-an-index/8586390#8586390

I was wondering yesterday if some query transform could help, good finding!

@aberenguel do you still have your original ocr-results.db to test above?

**Comment by hauck-jvsh** [comment] 2022-05-18 18:23
Sorry, I miss click on the close button on my mobile phone.

**Comment by aberenguel** [comment] 2022-05-18 18:54
> > I think this may worth a try https://stackoverflow.com/questions/8584499/sqlite-should-like-searchstr-use-an-index/8586390#8586390
> 
> I was wondering yesterday if some query transform could help, good finding!
> 
> @aberenguel do you still have your original ocr-results.db to test above?

Yes. Just tested here. Practically instantaneous. 
```
Execução finalizada sem erros.
Resultado: 1 linhas retornadas em 4 ms
Na linha 1:
SELECT id, text FROM ocr WHERE id >= '17407C1383410F8D233BF13F409550B6' AND id < '17407C1383410F8D233BF13F409550B7'
```

**Comment by lfcnassif** [comment] 2022-05-18 19:09
> Yes. Just tested here. Practically instantaneous.

Great, thank you, this is an easy change to apply! If I push it, could you test report generation again with your huge case to see if the DB writes will be a new bottleneck?

**Comment by aberenguel** [comment] 2022-05-18 19:11
Just changed to it. I'm going to test
```diff
diff --git a/iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/OCRParser.java b/iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/OCRParser.java
index 243e9cd8c..1f7910f9c 100644
--- a/iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/OCRParser.java
+++ b/iped-parsers/iped-parsers-impl/src/main/java/dpf/sp/gpinf/indexer/parsers/OCRParser.java
@@ -109,3 +109,3 @@ public class OCRParser extends AbstractParser {
 
-    private static final String SELECT_ALL = "SELECT id, text FROM ocr WHERE id LIKE ?;"; //$NON-NLS-1$
+    private static final String SELECT_ALL = "SELECT id, text FROM ocr WHERE id >= ? AND id < ?"; //$NON-NLS-1$
 
@@ -334,2 +334,3 @@ private static synchronized Connection getConnection(File outputBase) {
             conn = config.createConnection("jdbc:sqlite:" + db.getAbsolutePath());
+            conn.setAutoCommit(false);
             connMap.put(db, conn);
@@ -480,3 +481,4 @@ public static void copyOcrResults(String hash, File inputBase, File outputBase)
         try (PreparedStatement ps = getConnection(sourceDb.getParentFile()).prepareStatement(SELECT_ALL)) {
-            ps.setString(1, hash + "%"); //$NON-NLS-1$
+            ps.setString(1, hash);
+            ps.setString(2, hash.substring(0, hash.length() - 1)  + (char) (hash.charAt(hash.length() - 1) + 1));
             ResultSet rs = ps.executeQuery();
```

**Comment by lfcnassif** [comment] 2022-05-18 19:20
> autocommit flag

Good, this is not a trivial change, there is a reason to use autocommit, OCRParser could run in different external parsing processes and we should re-use OCR results from different processes. Furthermore, if processing crash and we use --continue, results of already committed items in the index should be also committed in OCR results DB.

**Comment by aberenguel** [comment] 2022-05-18 19:31
I think this fix eliminated the bottleneck. I'm generating the report. The `ocr-results.db` of the report is being created correctly and there are no idle workers anymore.

**Comment by aberenguel** [comment] 2022-05-18 19:35
Another thing I think that could be optimized is the addition of videos in the report when the flag thumbsOnly is selected. Look like the "mp4" are being extracted to temp dir. As only grid images of the video are important, the video itself should not be extracted. Anyway, it is a matter for another issue.

**Comment by lfcnassif** [comment] 2022-05-18 20:11
> I think this fix eliminated the bottleneck. I'm generating the report. The `ocr-results.db` of the report is being created correctly and there are no idle workers anymore.

Great!

> Look like the "mp4" are being extracted to temp dir. As only grid images of the video are important, the video itself should not be extracted

If I remember, although most processing results are reused when creating report, a few tasks are executed again over the videos, so iped would need the original file to process it. Just the ExportFileTask ignores the video content when exporting and export just the mosaic view...

**Closed** 2022-05-19 13:24 UTC
Labels: enhancement
