### ISSUE TITLE
Unsupported image type (EWF Version 2 (Ex01))

### ISSUE THREAD

**Issue by vitorlco** [sepinf-inc/IPED#2379] opened 2024-12-06 12:03 UTC
O Iped is reporting an error when processing forensic images in EX01 format. The error information follows:
2024-12-06 08:18:22     [ERROR] [engine.datasource.SleuthkitReader]                     org.sleuthkit.datamodel.TskCoreException: Errors occurred while ingesting image Image: 
2024-12-06 08:18:22     [ERROR] [engine.datasource.SleuthkitReader]                     1. Unsupported image type (EWF Version 2 (Ex01)) (Sector offset: 0) Image:

**Comment by lfcnassif** [comment] 2024-12-07 02:38
Could you please provide the full log? What OS are you using? Does it happen for any Ex01 image or just with a specific one? Which software generated the Ex01 image? Could you share an Ex01 sample image that reproduces the situation?

**Comment by vitorlco** [comment] 2024-12-09 15:35
Eu estou usando o Windows 11 e a imagem foi gerada pelo software forense MASSter SOLO4. O erro está ocorrendo com imagens grandes que são particionadas automaticamente na criação pelo software forense.

**Comment by wladimirleite** [comment] 2024-12-09 18:06
> The error is occurring with large images that are automatically partitioned upon creation by the forensic software.

Isn't there an option (in the forensic imaging tool you are using) to avoid image partitioning?

**Comment by lfcnassif** [comment] 2024-12-10 10:32
Could you please answer the remaining questions?

**Comment by lfcnassif** [comment] 2024-12-18 00:49
> MASSter SOLO4 forensic software

AFAIK it is a hardware, no? Could you share a test image that reproduces the issue? If not, could you test the last version of libewf project (https://github.com/libyal/libewf), ewfmount and ewfverify tools, on Linux e see if it fixes the issue?

**Comment by lfcnassif** [comment] 2024-12-21 13:18
Closing as can't reproduce. If you can share a sample image to reproduce the issue, please reopen.

**Closed by lfcnassif** 2024-12-21 13:18 UTC
Labels: need info, can't reproduce
