### ISSUE TITLE
DBX parser not working

### ISSUE THREAD

**Issue by thiagofuer** [sepinf-inc/IPED#1379] opened 2022-10-14 14:32 UTC
I'm not getting to decode DBX files on IPED4.0.1
Analyzing IPED-SearchApp.log file i found a error line about DBX parser:
"2022-10-14 09:52:47	[WARN]	[parsers.mail.OutlookDBXParser]			DBX parser not found, DBX mailboxes will NOT be expanded."
so my dbx files can`t be decode.
On IPED3 everything works fine.

Local config file:
![image](https://user-images.githubusercontent.com/1029909/195871649-3bba1477-f507-417b-a31a-07e06c4d7e16.png)

IpedSeach log error
![image](https://user-images.githubusercontent.com/1029909/195872222-376daa20-5914-4480-bf6d-55e0b8a21980.png)
IpedSearch full file
[IPED-SearchApp.log](https://github.com/sepinf-inc/IPED/files/9787257/IPED-SearchApp.log)

**Comment by lfcnassif** [comment] 2022-10-14 15:01
Did you keep the plugin folder side by side with iped 4.0 folder? This warning is expected, including in version 3.x, since the plugin is not copied to case folder, because it would be useless, DBX are expanded while processing. I would need your processing log, not the analysis one, to see possible issues with DBX parsing.

**Comment by lfcnassif** [comment] 2022-10-14 16:02
I can't reproduce, parsing my local DBX samples works with latest 4.0.5.

**Comment by thiagofuer** [comment] 2022-10-14 16:18
> Did you keep the plugin folder side by side with iped 4.0 folder? This warning is expected, including in version 3.x, since the plugin is not copied to case folder, because it would be useless, DBX are expanded while processing. I would need your processing log, not the analysis one, to see possible issues with DBX parsing.

Yes, the plugin folder is side by side with iped folder. i will try to reproduce on iped 4.0.5

**Comment by lfcnassif** [comment] 2022-10-14 17:05
4.0.1 also works fine here. I think there is something wrong with your "installation". If not, I need a triggering DBX sample to reproduce locally.

**Comment by thiagofuer** [comment] 2022-10-14 18:12
Same result on iped 4.0.5
![image](https://user-images.githubusercontent.com/1029909/195912730-36bfb871-f495-4ad3-a672-2f1e257b31ec.png)
i will sent proccess log by email

**Comment by thiagofuer** [comment] 2022-10-14 18:13
Same result on iped 4.0.5
![image](https://user-images.githubusercontent.com/1029909/195913590-e976234a-6934-4083-ad0d-6856fbc7db86.png)
i will sent proccess log by email

**Comment by lfcnassif** [comment] 2022-10-14 20:24
Thank you @thiagofuer for the logs sent privately. In one of them, there is:
`2022-10-14 14:05:23 [WARN] [parsers.standard.StandardParser] ParsingThread-0 Parsing exception: Caixa de entrada.dbx (6613716 bytes) java.nio.file.NoSuchFileException: E:\teste.txt`

I checked the plugin code, and there is no such reference, in any commit from history. Then I found this file in my E: drive. Deleting it, I was able to reproduce the bug...

I forced my mind, then I remembered about this temporary change to test #913, if the new security Policy would block unauthorized file access from plugins. Probably, I committed and pushed the patched artifact generated for testing purposes to the remote repo by mistake.

Thank you for reporting this, I'll push a fixed version of the DBX plugin.

**Comment by thiagofuer** [comment] 2022-10-14 20:39
kkk that's happens with all programers...
Thanks for your help!!

**Comment by lfcnassif** [comment] 2022-10-14 21:33
Different from commercial and some other open source tools, this project tries to be 100% transparent to the user and report everything in the release notes, so I put here a detailed explanation about my fault. I think this is important for transparency, reproducibility and auditability of results.

**Closed** 2022-10-14 21:48 UTC
Labels: bug

**Comment by lfcnassif** [comment] 2022-10-14 21:51
If you could test, you can find a fixed plugin version here:
https://gitlab.com/iped-project/iped-maven/-/blob/master/net/sf/java-dbx/1.1-p6/java-dbx-1.1-p6.jar

Remove the previous 1.1-p5 version from your plugin folder when putting the new one.

**Comment by thiagofuer** [comment] 2022-10-14 22:05
It works very well
Thanks for your support
![image](https://user-images.githubusercontent.com/1029909/195950522-ba8edb9a-89b5-4a8c-968c-a57f9c825993.png)

**Comment by gilmaralves** [comment] 2022-10-16 12:42
I'm who, firstly, asked @thiagofuer for help about this issue.
Today, I've processed again the image using the fixed plugin and all is working fine.

before: 
![IPED - bug não corrigido](https://user-images.githubusercontent.com/3689932/196035744-f3181a28-a66a-48c9-9681-47570b3625c3.png)

after fixing the bug:
![IPED - bug corrigido](https://user-images.githubusercontent.com/3689932/196035769-58500389-641a-4648-a39a-098629a3fa1e.png)

All messages in *.dbx files were parsed.
