### ISSUE TITLE
Item from UFDR being extracted three times

### ISSUE THREAD

**Issue by hauck-jvsh** [sepinf-inc/IPED#1685] opened 2023-05-16 17:28 UTC
I process a case and the same is extracted three times from the same database. As you may see from the screenshot I take the item is exactly the same, having the same globaId.

![printIPED](https://github.com/sepinf-inc/IPED/assets/67768441/c002191a-5eb9-48a9-9ee6-635794138d12)

**Comment by lfcnassif** [comment] 2023-05-16 17:46
Are you able to always reproduce? Could you investigate this?

**Comment by hauck-jvsh** [comment] 2023-05-16 17:55
> Are you able to always reproduce? Could you investigate this?

I don't known, I will try again to check if the same thing occurs again. I can look after this, but it will take some time.

**Comment by tc-wleite** [comment] 2023-05-16 17:58
> I don't known, I will try again to check if the same thing occurs again. I can look after this, but it will take some time.

I can look at this if you are busy. Just send me the UFDR.

**Comment by hauck-jvsh** [comment] 2023-05-16 18:27
I'm processing it to see if the problem occurs again.  I say that it will took some time because I never did anything related with the UFDR extraction. Anyway I can share the UFDR with you. Can I put it in our storage and share the folder with you?

**Comment by hauck-jvsh** [comment] 2023-05-17 16:06
I think that it appears three times in UFDR xml, I search the hash and found 3 occurrences in the xml.
![image](https://github.com/sepinf-inc/IPED/assets/67768441/a0e3db8b-3dd0-4dba-ab24-ba4be9123e7a)
![image](https://github.com/sepinf-inc/IPED/assets/67768441/3ea54206-7ca7-48b0-9ccc-a880b76a086d)
![image](https://github.com/sepinf-inc/IPED/assets/67768441/688d6d12-4b9b-4963-8bcd-babe835b5147)

**Comment by lfcnassif** [comment] 2023-05-17 23:39
Currently we try to filter out duplicate "FS Files" referenced multiple times in the UFDR main xml file. For example, a file can be present in the Files section and also in the Chat section (a chat attachment). Interestingly some files can be present in the Chat section but not in the FS Files section...

Anyway, the trackID should be unique into the case and this should be fixed. I think ignoring items with the same ufed:id should fix this. But be careful, the references should be kept (e.g. if the ignored item was a chat attachment, a chat attachment reference should be created to the main item)

**Comment by lfcnassif** [comment] 2023-05-18 03:32
> But be careful, the references should be kept

PS: A logic for this already exists in UFEDXmlReader and maybe it only needs to be applied to more UFDR extracted entities/categories.

**Comment by lfcnassif** [comment] 2023-05-18 13:26
Yes, MindFusion XML Viewer

**Comment by hauck-jvsh** [comment] 2023-05-22 16:38
I think that this fix the cases of files with the same trackId

**Comment by lfcnassif** [comment] 2023-06-01 03:02
Reopening, this was closed accidentally because of being mixed in #1702.

**Closed** 2023-10-21 03:23 UTC
Labels: bug
