### ISSUE TITLE
Improve detection of Apple iWork documents

### ISSUE THREAD

**Issue by joao-fernando** [sepinf-inc/IPED#1793] opened 2023-08-01 18:31 UTC
Hello!

Apple iWork documents are being detected with `application/vnd.apple.unknown.13` `contentType` and being identified as zip files:
![image](https://github.com/sepinf-inc/IPED/assets/54771774/5b2e50e6-b5c9-4165-bacc-63a2a5a272ec)
![image](https://github.com/sepinf-inc/IPED/assets/54771774/231485e3-d477-4658-87c8-9d6adcd5ce3c)

When I export these files, they are saved as _filename.numbers.zip_

I've seen this behavior with Numbers, Page and Keynote documents.

**Comment by lfcnassif** [comment] 2023-08-01 18:41
This may be related to Tika library. Could you share some samples for testing and to validate a possible enhancement?

**Comment by lfcnassif** [comment] 2023-08-02 11:37
Thanks!

**Comment by joao-fernando** [comment] 2023-08-02 13:05
I was testing tika on my computer and using version 2.4.0 directly on the command line the content-type is correctly detected.
![image](https://github.com/sepinf-inc/IPED/assets/54771774/55ba9d75-1fb5-470e-ae35-c50cbea1ffef)

**Comment by lfcnassif** [comment] 2023-08-02 14:29
Hum, thanks for testing. I was going to test last Tika version, so that seems not necessary. Maybe Tika is giving different results if the input is a File or if input is a byte stream, I have seen this before... I will try to do some tests when I have some time.

**Comment by lfcnassif** [comment] 2023-08-03 13:42
Had time to take a look. I got the same Tika GUI client output you got. But running detection on the command line I got:
![image](https://github.com/sepinf-inc/IPED/assets/7276994/caa23074-a764-44ce-bdf3-6979d2a2edb6)

Investigating, I found 2 issues here:
- There are 2 Tika iWork parsers missing in our `ParseConfig.xml` file: `org.apache.tika.parser.iwork.iwana.IWork13PackageParser` and `org.apache.tika.parser.iwork.iwana.IWork18PackageParser`
- Some parsers, like the 2 above, specialize the mediaType identified in the Signature detection step (`application/vnd.apple.unknown.13` in this case) while parsing, this is not new to me. Unfortunately parsing is done after signature detection and categorization in IPED processing pipeline and specialized types returned by parsers are ignored today. Some parsers also depend on categorization (e.g. to decide if the file is a container to be expanded). I'm not sure how to workaround this, running categorization (and RefineCategoryTask.js?) again is an approach, but it doesn't seem the perfect solution...

**Comment by lfcnassif** [comment] 2023-08-03 15:00
> Unfortunately parsing is done after signature detection and categorization in IPED processing pipeline

The "set true extension" step is also executed before parsing.

**Comment by lfcnassif** [comment] 2023-08-09 02:11
Just tested Tika detection programmatically in a standalone program, result was the same I got using the command line: application/vnd.apple.unknown.13

I also tested explicitly Tika's IWorkDetector, since it has specific code to detect iWork 13 and 18 files:
https://github.com/apache/tika/blob/main/tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-apple-module/src/main/java/org/apache/tika/detect/apple/IWorkDetector.java

Result was the same: application/vnd.apple.unknown.13

Following above method calling stack, this is the important detection block into IWork13PackageParser:
```
        public static MediaType detectIfPossible(ZipEntry entry) {
            String name = entry.getName();
            if (!name.endsWith(".iwa")) {
                return null;
            }

            // Is it a uniquely identifying filename?
            if (name.equals("Index/MasterSlide.iwa") || name.startsWith("Index/MasterSlide-")) {
                return KEYNOTE13.getType();
            }
            if (name.equals("Index/Slide.iwa") || name.startsWith("Index/Slide-")) {
                return KEYNOTE13.getType();
            }

            // Is it the main document?
            if (name.equals("Index/Document.iwa")) {
                // TODO Decode the snappy stream, and check for the Message Type
                // =     2 (TN::SheetArchive), it is a numbers file;
                // = 10000 (TP::DocumentArchive), that's a pages file
                return UNKNOWN13.getType();
            }

            // Unknown
            return null;
        }
```

I found `Index/Document.iwa` into the samples. So the TODO above means this is a Tika known limitation (not a bug).

And Tika is able to detect the type while parsing just because of the file extension:
https://github.com/apache/tika/blob/bf5da6691a7bf1044896e1c97f54c2ff94a8a422/tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-apple-module/src/main/java/org/apache/tika/parser/iwork/iwana/IWork13PackageParser.java#L111

Removing the extension from the provided samples, they are detected as application/vnd.apple.unknown.13 by Tika App GUI.

I think we can also refine the file types based on extension at least, I'll try to implement.

**Comment by lfcnassif** [comment] 2023-08-09 03:24
Commits above worked, iWork 13 files were correctly classified based on extension. But they brought a side effect: since those files are not put in "Compressed Files" category anymore, they stopped to be expanded by default. That resulted in less extracted information, since a lot of images weren't extracted anymore (and surprisingly some PDF files from the pages document). That is expected and user can also configure Documents/Spreadsheets/Presentations to be expanded if desired.

**Comment by lfcnassif** [comment] 2023-08-09 03:31
Closed by commits:
[1abb3aa](https://github.com/sepinf-inc/IPED/commit/1abb3aad414820e355cb31cc5c852de24d2ec98c)
[6249cfa](https://github.com/sepinf-inc/IPED/commit/6249cfa708e294a6bfe7d1f6077d48e1565b25d4)
[58f2d10](https://github.com/sepinf-inc/IPED/commit/58f2d101649c9dd1ee43cc93ae59d14cf9806f1b)
[a545321](https://github.com/sepinf-inc/IPED/commit/a545321a1b6ad5f374277953a59cd2a9683bd866)

**Closed by lfcnassif** 2023-08-09 03:31 UTC
Labels: enhancement

**Comment by lfcnassif** [comment] 2023-08-09 13:28
I didn't saw that entry, I think it should. Could you report the issue directly to Tika project?

**Comment by lfcnassif** [comment] 2023-08-09 18:09
If you have a sample keynote file without sensitive info possible to share publicly, I can report the issue in Tika Jira.

**Comment by joao-fernando** [comment] 2023-08-09 18:19
I don't have one available now.
I'll try to create one later.

**Comment by tc-wleite** [comment] 2023-08-09 21:12
> If you have a sample keynote file without sensitive info possible to share publicly, I can report the issue in Tika Jira.

I have a few keynotes here, but I am not sure if they trigger the issue.

[keynote.zip](https://github.com/sepinf-inc/IPED/files/12306960/keynote.zip)

**Comment by lfcnassif** [comment] 2023-08-09 23:08
> I have a few keynotes here, but I am not sure if they trigger the issue.
> 
> [keynote.zip](https://github.com/sepinf-inc/IPED/files/12306960/keynote.zip)

Thanks @tc-wleite! I was able to reproduce with your files after removing their extension. I'll open an issue at Tika and point it here for reference.

**Comment by lfcnassif** [comment] 2023-08-09 23:24
Took a look at Tika code again and I think I know what is happening, I'll report directly there.

**Comment by lfcnassif** [comment] 2023-08-09 23:42
Tika issue, explanation and fix to be applied:
https://issues.apache.org/jira/browse/TIKA-4111

**Comment by lfcnassif** [comment] 2023-08-10 22:54
> Tika issue created, explanation and tested fix to be applied:
> https://issues.apache.org/jira/browse/TIKA-4111

Just fixed it on Tika. Took much more work than expected, some tests started to fail, but seems good now.
