### ISSUE TITLE
Processing interrupted

### ISSUE THREAD

**Issue by igiuseppem** [sepinf-inc/IPED#1624] opened 2023-04-09 07:00 UTC
Good morning.
I processed a forensic copy of an hard disk with the latest version of IPED (downloaded yesterday, via command line). The processing started correctly but, despite the remaining time indicated, suddenly finished with no error in the MS-DOS prompt. Running the processed copy, IPED shows the following message
![image](https://user-images.githubusercontent.com/96940535/230758891-e446544d-4031-4489-bde6-ba87b880fc19.png)
I used the --continue option 4 times and it added new elements each time. Although with the last attempt it didn't added new files, so I thought it has completed all the parsing, running the processed copy, IPED keep telling that the processing didn't finished successfully.

Kind regards
Giuseppe

**Comment by lfcnassif** [comment] 2023-04-09 12:15
Could you share the first and last processing logs? If they have sensitive data, you can send them to my email in my profile.

And was a file called hs_err_pidXXXX.log created in the folder from where you executed the processing? If yes, send it too please.

**Comment by igiuseppem** [comment] 2023-04-10 07:43
Dear Luis,

I have just sent the logs via mail. No, there isn't a file called hs_err_pidXXXX.log

Thank you very much

**Comment by lfcnassif** [comment] 2023-04-10 12:23
Thank you @igiuseppem, I just answered you. Unfortunately I didn't find any clues in your logs about what stopped processing. And if no hs_err_pidXXXX.log file (where XXXX is a number) was created, my guess is that another program stopped the application. Please take a look at your antivirus logs.

**Comment by lfcnassif** [comment] 2023-04-11 12:40
Was the message `IPED-4.1.1 finished.` printed on the Console? If not, the processing didn't finish completely and something is causing the processing to abort abruptly, without giving any chance to the application to log.

Does this happen with another forensic image? Does this happen if you process the forensic image on another machine?

PS: The logs of 4.1.1 version may help.

**Comment by igiuseppem** [comment] 2023-04-16 08:31
Hi Luis.

1) No, the message "IPED finished." was not printed on the console
2) I processed another forensic image on the same laptop and it doesn't happen
3) I have processed the same forensic image on another workstation and I obtained exactly the same result.

I have just sent via mail the 3 logs of the processing with IPED 4.1.1 on the first workstation.

Kind regards

**Comment by lfcnassif** [comment] 2023-04-17 14:42
Thank you @igiuseppem. Unfortunately I still can't see clues in the logs about what is happening. Please check again if `hs_err_pid<pid>.log` files were created in the current directory (the directory from where you executed the application in the console), they are often created when the application crashes abruptly.

If they weren't created, I guess something external to the application stopped it. Please take a look at the Windows Event logs searching for something that could have closed the IPED application near its stopping time.

If you find nothing, the only way I can help you investigating this is if you are able to share the problematic forensic image privately with me, I see no other option...

**Comment by igiuseppem** [comment] 2023-04-17 17:25
Thank you @lfcnassif.
The hs_err_pid<pid>.log was not created, but in the Windows Event logs I think I found useful information. Very near the time IPED "completed" the processing, I found this error (it's the first of the three times IPED stopped):
"Faulting application name: java.exe, version: 11.0.13.0, timestamp: 0x616c78af
Faulting module name: ntdll.dll, version: 10.0.22621.1344, timestamp: 0x8381da15
Exception code: 0xc00000fd
Error offset 0x0000000000021110
Process ID that generated the error: 0x0x694
Start time of the application that generated the error: 0x0x1D96BB272D0DA09
Path to the Faulting Application: C:\Users\admin\.iped\jre-11.0.13\bin\java.exe
Path to the module that generated the error: C:\WINDOWS\SYSTEM32\ntdll.dll
Report ID: 9a2d1abf-3e75-4fd8-a5d7-c964df656f20
Full package name that generated the error:
Application ID of the package that generated the error:"
If you need that I post the other 2 events, corresponding at when IPED interrupted the processing, I will do it.

**Comment by lfcnassif** [comment] 2023-04-17 21:34
Thanks @igiuseppem. So seems this is being caused by a native library call. Usually these kind of errors come from the Sleuthkit, although IPED uses other native libraries (hs_err_pid.log files could point us to the right one...). Could you run Sleuthkit tsk_loadbdb.exe application on the problematic image to see if it finishes OK? It can be downloaded from https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.12.0

**Comment by lfcnassif** [comment] 2023-04-18 16:15
> You are welcome @lfcnassif . I have used tsk_loaddb.exe and it finished in seconds, creating a .db file. I don't see a log. How can I know if it has completed without errors?

Thanks @igiuseppem. Have tsk_loaddb.exe printed a message like `Database stored at: XXXXXX` on the console?

If not, it crashed and the issue is within TSK. In this case, a workaround is exporting the image contents to an AD1 logical image using FTKImager and processing the AD1 with IPED, that will skip TSK processing and should bypass the issue.

If yes, there is another native library causing the issue. In this case, I suggest you to go to conf/ParsingTaskConfig.txt and turn the option `enableExternalParsing` on, that should isolate issues with other native libraries used for file parsing.

**Comment by igiuseppem** [comment] 2023-04-18 17:31
yes, on the console I can see the message like Database stored at: XXXXXX. So, I will try the option enableExternalParsing.

**Comment by igiuseppem** [comment] 2023-04-19 04:12
@lfcnassif, I took your advice and finally I have the "IPED finished." message. The processed copy runs correctly as well. Thank you very very much!

**Comment by lfcnassif** [comment] 2023-04-20 00:26
You're welcome @igiuseppem. We didn't find the actual bug, but since this is not easily reproducible and there is an existing workaround, I'll close this.

**Closed by lfcnassif** 2023-04-20 00:26 UTC
Labels: need info, can't reproduce
