### ISSUE TITLE
Hitting NPE in ThumbTask

### ISSUE THREAD

**Issue by fmpfeifer** [sepinf-inc/IPED#514] opened 2021-05-06 01:12 UTC
While working on #486, I came across a NPE while processing a Cellebrite Physical Analyzer XML Report.

some stack trace:
```
2021-05-04 13:58:14	[INFO]	[indexer.process.Worker]			Worker-35 interrupted on [queue-end] (null bytes)
2021-05-04 13:58:15	[ERROR]	[gpinf.indexer.IndexFiles]			Processing Error: 
java.lang.Exception: Worker-10 Error while processing Report/_DecodedData/InstantMessage/InstantMessage_b5cb1ffa-65f4-4489-8c43-4bf6d3ba6962//var/tmp/com.apple.messages/com.apple.MobileSMS/Media/A7B8F608-44FC-4F47-9769-04FCFF16A485/IMG_9928.HEIC (nullbytes)
	at dpf.sp.gpinf.indexer.process.Worker.process(Worker.java:188) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:240) ~[iped-engine-4.0.0-snapshot.jar:?]
Caused by: java.lang.NullPointerException
	at dpf.sp.gpinf.indexer.process.task.ThumbTask.hasThumb(ThumbTask.java:37) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.ImageThumbTask.process(ImageThumbTask.java:222) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processMonitorTimeout(AbstractTask.java:241) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:173) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:218) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:181) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:218) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:181) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:218) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:181) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:218) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:181) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.sendToNextTask(AbstractTask.java:218) ~[iped-engine-4.0.0-snapshot.jar:?]
	at dpf.sp.gpinf.indexer.process.task.AbstractTask.processAndSendToNextTask(AbstractTask.java:181) ~[iped-engine-4.0.0-snapshot.jar:?]
```
This aborts the processing.

It looks like the evidence object being passed to  [ThumbTask.hasThumb](https://github.com/sepinf-inc/IPED/blob/b44ada688749f29347df03490e2c31f3f0c85f55/iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/ThumbTask.java#L35) has all attributes as null values. See the "null bytes" after the exception (it should be evidence.getLength() bytes).

I was able to get it out of my way by checking for null hash in  [ThumbTask.hasThumb](https://github.com/sepinf-inc/IPED/blob/b44ada688749f29347df03490e2c31f3f0c85f55/iped-engine/src/main/java/dpf/sp/gpinf/indexer/process/task/ThumbTask.java#L35), as follows (third line):

```
protected boolean hasThumb(IItem evidence, File thumbFile) throws Exception {
    if (thumbFile == null) {
        if (evidence.getHashValue() != null ) {
            Connection con = ExportFileTask.getSQLiteStorageCon(output, evidence.getHashValue().getBytes());
            try (PreparedStatement ps = con.prepareStatement(SELECT_THUMB)) {
```

but I feel like I'm treating the symptoms, not the cause. I'm not sure why this evidence object is coming like that.
Tested with IPED 3.18.5, and this bug doesn't happen.
Tested many times to see if it could be a race condition, but it fails reliably at the same item every time.

Maybe it is possible to bisect that, but it would take a long time, as this case is huge and the NPE is triggered towards the end of the processing.

Any ideas?

**Comment by lfcnassif** [comment] 2021-05-06 02:20
Possibly this is the new queue-end item being passed through the pipeline, see #362. ThumbTask was also change recently, not sure what of those caused this, will look at this tomorrow.

**Comment by lfcnassif** [comment] 2021-05-06 02:23
That is the queue-end item, it is in the trace. It must be ignored by single-item tasks, should be simple to fix.

**Comment by tc-wleite** [comment] 2021-05-06 03:27
Taking a quick look here, the issue may be related to an item with hash="" (empty string).
In this case, evidence.getHash() return is not null (so the item won't be ignored in the beginning of process()), but evidence.getHashValue() returns null (triggering the NPE @fmpfeifer reported).

**Comment by fmpfeifer** [comment] 2021-05-06 11:57
I managed to debug and set a breakpoint in the catch block of the process method of the Worker class. Than it was possible to inspect the evidence object that triggered the NPE:

![image](https://user-images.githubusercontent.com/3900238/117294349-ee127f00-ae48-11eb-8ec1-fbda84dc8f91.png)

@tc-wleite: it is really the case of hash=""

**Comment by lfcnassif** [comment] 2021-05-06 16:47
Items could have an empty hash e.g.: database records or ufdr items with length > 0 but pointing to no content (maybe an item recovered with just metadata, without the data). Will push a fix.

**Comment by lfcnassif** [comment] 2021-05-06 16:52
@fmpfeifer could you confirm this item has no content on CellebriteReader?

**Comment by lfcnassif** [comment] 2021-05-06 16:57
For items without content (different from 0 length content), usually the hash string is set to "", otherwise HashTask would compute a hash for an EmptyInputStream, resulting in a hash of zero length files.

**Comment by tc-wleite** [comment] 2021-05-06 17:02
I manage to reproduce the error here, but in a large case. I was trying to isolating it.
In my case it was a subitem of a carved ZIP file.
@lfcnassif, I fixed it locally changing the test condition `item.getHash() == null` in `process(IItem item) ` to `item.getHashValue() == null`, in `DocThumbTask`, `ImageThumbTask `and `VideoThumbTask`.

**Comment by lfcnassif** [comment] 2021-05-06 17:09
Well I did a similar fix, we should have assigned this to someone to avoid duplicate work... your fix is better because it does not use a new import. If your item really does not have a content, please commit, thanks!

**Comment by lfcnassif** [comment] 2021-05-06 17:12
@fmpfeifer's item probably will have no content, length is null, should be your case too.

**Closed** 2021-05-06 17:48 UTC
Labels: bug

**Comment by fmpfeifer** [comment] 2021-05-06 17:57
The only reference for that path in my report.xml is:
```
<multiModelField name="Attachments" type="Attachment">
  <model type="Attachment" id="235e7c4f-ee02-4966-8234-42c3165a0df9" deleted_state="Intact" decoding_confidence="High" isrelated="False" source_index="1575958" extractionId="0">
    <field name="UserMapping" type="DecodingSourceOptions">
      <value type="DecodingSourceOptions"><![CDATA[Decoding]]></value>
    </field>
    <field name="Filename" type="String">
      <value type="String"><![CDATA[/var/tmp/com.apple.messages/com.apple.MobileSMS/Media/A7B8F608-44FC-4F47-9769-04FCFF16A485/IMG_9928.HEIC]]></value>
    </field>
    <field name="ContentType" type="String">
      <value type="String"><![CDATA[image/heic]]></value>
    </field>
    <field name="Charset" type="String">
      <empty />
    </field>
    <dataField name="Data" type="MemoryRange">
      <empty />
    </dataField>
    <field name="URL" type="String">
      <empty />
    </field>
    <field name="Title" type="String">
      <value type="String"><![CDATA[IMG_9928.HEIC]]></value>
    </field>
  </model>
</multiModelField>
```

there is a file with the same name (`IMG_9928.HEIC`), but in a different folder, apparently unrelated.
Good to know it is now fixed. 
Thanks

**Comment by lfcnassif** [comment] 2021-05-13 13:20
Just to let you know, I think this was caused by 6c02a255cda9427e4e531a6c48a4b4423ad2dc0b.
