### ISSUE TITLE
Improvement suggestion: Possibility to correct automatic transcriptions.

### ISSUE THREAD

**Issue by wedersonrsouza** [sepinf-inc/IPED#1229] opened 2022-07-22 12:27 UTC
First of all, congratulations for including the possibility of automatic transcription of the audios.

Second, it would be very important to have the possibility for the analyst to correct the transcript. That would help a lot. As it is, it is necessary to copy it to another software and only then improve the transcript before including it in the report.

**Comment by lfcnassif** [comment] 2022-07-22 13:15
Closing, duplicate of #696. Please check the issue database before opening a new one.

If you are using the new default Vosk local audio transcription, we are working on a much better quality one here: #1227

If you can help testing, a snapshot can be found here:
https://github.com/sepinf-inc/IPED/actions/runs/2715522100

But it is several times slower than Vosk, you would be better using a good GPU.

**Closed by lfcnassif** 2022-07-22 13:15 UTC
