### ISSUE TITLE
Problem importing NSRL

### ISSUE THREAD

**Issue by ruanmichelmd** [sepinf-inc/IPED#7] opened 2017-10-02 15:54 UTC
Boa tarde,

Como utilizar a base NSRL? Baixei os arquivos do site deles, mas não contém arquivos .db, como sugere o arquivo de configuração. Tentei importar o que estão lá, mas dá erro. Qual o procedimento correto?

**Comment by lfcnassif** [comment] 2017-10-02 23:52
Descomente a opção kffdb no arquivo de configuração para indicar o local de instalação da base. Após execute Java -jar iped.jar -importkff pasta_nsrl_descompactada

**Comment by ruanmichelmd** [comment] 2017-10-03 18:34
Consegui rodar, mas sempre dá esse erro da imagem já no finalzinho. Apesar de tudo, ele ainda gera o arquivo kff.db. Como acabar com esse erro?
![erro_import_kff](https://user-images.githubusercontent.com/32461049/31142283-369e4158-a850-11e7-8f47-51f120d12c48.png)

**Comment by lfcnassif** [comment] 2017-10-03 19:57
Você deve substituir pasta_nsrl_descompactada pela pasta que contém o arquivo NSRLFile.txt.
Exibiu uma janela de progresso importando a base? Caso sim, provavelmente há uma incompatibilidade com a versão da base NSRL baixada. A última versão testada foi a NSRL 2.51

**Comment by ruanmichelmd** [comment] 2017-10-03 20:00
Exibiu a janela de progresso sim, e no final dela, apareceu esse erro. Mas estou conseguindo processar com a base que foi gerada assim mesmo, e vi que houve uma melhora no processamento. Depois vou testar com a NSRL 2.51. Obrigado pela atenção!

**Comment by lfcnassif** [comment] 2020-01-08 15:26
Please, check if the NSRL was downloaded correctly, maybe it was corrupted. After that, try the last 3.17-rc3 version to see if the issue is still present. Please reopen if any problem is found.

**Comment by fcscoutinho** [comment] 2022-06-25 16:37
I already changed the localconfig.txt and enabled the following:

# Full path for IPED hash database. It is highly recommended to store it on a fast disk,
# preferably used, and not the same as "indexTemp", if other disk is available.
hashesDB = E:\KFF\kff.db

However, the following error still occurs:

**E:\IPED_24062022\iped-4.0.0-beta>iped.exe -importkff E:\IPED_Aux\Diskprint_Kaspersky\RDS
Error: Was passed main parameter '-importkff' but no main parameter was defined in your arg class**

**Comment by lfcnassif** [comment] 2022-06-25 17:07
Have you read the migration guide I pointed out in the other issue?

**Comment by fcscoutinho** [comment] 2022-06-25 19:36
This: [java -jar lib/iped-hashdb.jar](https://github.com/sepinf-inc/IPED/wiki/Migration-from-3.18-to-version-4.0)

Yes, but it's not working with the settings I made...

IpedConfig.txt (# Enables file hashes calculation.
enableHash = true)

HashDBLooup.txt (# Excludes from the rest of processing (and from the case) known files according to hashes database (hash:status = known).
excludeKnown = false)

HashTaskConfig.txt (# To calculate multiple hashes use ; as separator
# Possible values: md5, sha-1, sha-256, sha-512 and edonkey
hashes = md5; sha-1; sha-256)

**Comment by tc-wleite** [comment] 2022-06-26 00:24
@fcscoutinho, [java -jar lib/iped-hashdb.jar](https://github.com/sepinf-inc/IPED/wiki/Migration-from-3.18-to-version-4.0) should be used to import files into a SQLite file, which will be later used during processing.
The options you mentioned has no effect in HashDB importing tool.

>> Yes, but it's not working with the settings I made...

What exactly didn't work?

**Comment by lfcnassif** [comment] 2022-06-26 01:42
I reopened this by accident, closing... @fcscoutinho you can answer @tc-wleite questions here or, even better, in discussions section as this doesn't seem an issue but usage doubts.

**Closed by lfcnassif** 2022-06-26 01:42 UTC

**Comment by lfcnassif** [comment] 2022-06-27 14:35
@tc-wleite I've just update the wiki about the iped-hashdb.jar hash import tool trying to make things even clearer, please take a look.

**Comment by tc-wleite** [comment] 2022-06-27 18:36
> @tc-wleite I've just update the wiki about the iped-hashdb.jar hash import tool trying to make things even clearer, please take a look.

I checked the changes, and it looks clearer now.
