### ISSUE TITLE
Unrecognized Partitions

### ISSUE THREAD

**Issue by Descadeirado** [sepinf-inc/IPED#1609] opened 2023-03-29 14:34 UTC
Recently I had a case that had one unrecognized partition in the disk binary image, which is shown with tools like FTK Imager. After processing the image with IPED, it does not show it.
I would like to see if it is possible for IPED to also show, in the "Evidences" tab, non recognized partitions with their size and a warning like: "partition with only "0"s",  "partition with possible encrypted content" (veracrypt, bitlocker, filevault).
Thanks

**Comment by lfcnassif** [comment] 2023-03-29 16:52
Wasn't the unrecognized partition listed in the Evidences tab? that should work and works with a image I have here. If the answer is "yes", could you provide a sample image which reproduces the issue?

Warning about possible encryption is already done on the command line and we already have an open improvement to list them in the "Possible encryption by entropy" filter, see #1072.

**Comment by lfcnassif** [comment] 2024-03-12 11:38
Closing as can't reproduce. If you can provide a sample image to reproduce the described behavior, please reopen.

**Closed by lfcnassif** 2024-03-12 11:38 UTC
Labels: need info
