### ISSUE TITLE
Error importing graph database

### ISSUE THREAD

**Issue by aberenguel** [sepinf-inc/IPED#1059] opened 2022-04-08 17:16 UTC
The version 4.0.0-snapshot is showing this error in the end of processing (it was used a simple ZIP file, but it happened with other input data files).

```
Running /home/berenguel/opt/java/liberica/jdk-11.0.14.1-full/bin/java -cp /home/berenguel/git/IPED/target/release/iped-4.0.0-snapshot/lib/* org.neo4j.cli.AdminTool import --input-encoding utf-8 --bad-tolerance 0 --database graph.db --ignore-empty-strings true --skip-duplicate-nodes true --nodes=nodes_DOCUMENT_headers_iped.csv,nodes_DOCUMENT_iped.csv
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                     Exception in thread "main" java.lang.NoSuchFieldError: COMMAS
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at org.neo4j.importer.ImportCommand.<clinit>(ImportCommand.java:84)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at org.neo4j.importer.ImportCommandProvider.createCommand(ImportCommandProvider.java:35)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at org.neo4j.importer.ImportCommandProvider.createCommand(ImportCommandProvider.java:29)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at org.neo4j.cli.AdminTool.lambda$registerCommands$0(AdminTool.java:112)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at org.neo4j.cli.AdminTool.registerCommands(AdminTool.java:112)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at org.neo4j.cli.AdminTool.getCommandLine(AdminTool.java:103)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at org.neo4j.cli.AdminTool.execute(AdminTool.java:87)
2022-04-08 14:09:53     [INFO]  [labld.graph.GraphImportRunner$InputReader]                             at org.neo4j.cli.AdminTool.main(AdminTool.java:79)
2022-04-08 14:09:53     [ERROR] [labld.graph.GraphGenerator]                    Error generating database.
java.lang.RuntimeException: Could not import graph database.
        at br.gov.pf.labld.graph.GraphImportRunner.run(GraphImportRunner.java:113) ~[iped-engine-4.0.0-snapshot.jar:?]
        at br.gov.pf.labld.graph.GraphGenerator.importDB(GraphGenerator.java:66) [iped-engine-4.0.0-snapshot.jar:?]
        at br.gov.pf.labld.graph.GraphGenerator.generate(GraphGenerator.java:34) [iped-engine-4.0.0-snapshot.jar:?]
        at br.gov.pf.labld.graph.GraphGenerator.generate(GraphGenerator.java:30) [iped-engine-4.0.0-snapshot.jar:?]
        at br.gov.pf.labld.graph.GraphTask.finishGraphGeneration(GraphTask.java:161) [iped-engine-4.0.0-snapshot.jar:?]
        at br.gov.pf.labld.graph.GraphTask.finish(GraphTask.java:190) [iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.finishTasks(Worker.java:124) [iped-engine-4.0.0-snapshot.jar:?]
        at dpf.sp.gpinf.indexer.process.Worker.run(Worker.java:297) [iped-engine-4.0.0-snapshot.jar:?]
```

**Comment by lfcnassif** [comment] 2022-04-08 22:48
I'm not able to reproduce this on Windows. Seems to be some class incompatibility issue. Have you done a mvn **clean** install after switching between 3.18.x and master branches?

**Comment by aberenguel** [comment] 2022-04-08 22:54
Sorry. My mistake. The lib folder was not clean. The maven added new jars and I did not clean the folder before.
```
lib/neo4j-3.5.30.jar  lib/neo4j-4.4.4.jar ...
```

**Comment by lfcnassif** [comment] 2022-04-08 22:58
Different jars in lib folder may not be the cause, because just the right jar version is used, others are ignored. But that is a clue that a clean install was not done, so while compiling, old class versions should have been used in the building process.

**Comment by lfcnassif** [comment] 2022-04-08 23:02
So I'm closing this, please reopen if the issue persists after a clean install.

**Closed by lfcnassif** 2022-04-08 23:02 UTC
Labels: invalid
