### ISSUE TITLE
Indexador\Index Access denied :bug: 

### ISSUE THREAD

**Issue by CupOfCoke** [sepinf-inc/IPED#695] opened 2021-08-13 09:25 UTC
Hi, 
I am running IPED in a Windows 10 VM (12 virtual cores & 32 GB RAM) with an additional SSD Temp Disk. Both the VM Disk and the Temp Disk are virtual SSDs running on actual SSDs. The data source and destination are on a Samba Share which is mounted in Windows for Users and Admins. During the Analysis Process I get an Error saying "Access denied". The Error occurs since Version 3.18.7. Here is the part of the corresponding log:

`2021-08-12 19:37:22     [ERROR] [gpinf.indexer.IndexFiles]                      Processing Error:
java.io.FileNotFoundException: ..\..\<PATH>\IPED\indexador\index\segments_1 (Access is denied)
        at java.io.FileOutputStream.open0(Native Method) ~[?:1.8.0_152]
        at java.io.FileOutputStream.open(Unknown Source) ~[?:1.8.0_152]
        at java.io.FileOutputStream.<init>(Unknown Source) ~[?:1.8.0_152]
        at dpf.sp.gpinf.indexer.util.IOUtil.copiaArquivo(IOUtil.java:204) ~[iped-utils-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.util.IOUtil.copiaArquivo(IOUtil.java:199) ~[iped-utils-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.util.IOUtil.copiaDiretorio(IOUtil.java:239) ~[iped-utils-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.util.IOUtil.copiaDiretorio(IOUtil.java:245) ~[iped-utils-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.finalizarIndexacao(Manager.java:600) ~[iped-engine-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.process.Manager.process(Manager.java:234) ~[iped-engine-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.startManager(IndexFiles.java:196) [iped.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.execute(IndexFiles.java:249) [iped.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:319) [iped.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_152]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_152]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_152]
        at dpf.sp.gpinf.indexer.util.CustomLoader.run(CustomLoader.java:65) [iped-engine-3.18.7.jar:?]
        at dpf.sp.gpinf.indexer.IndexFiles.main(IndexFiles.java:315) [iped.jar:?]

ERROR!!!`

The current Workaround for me is to open the Windows Explorer and the security options of the output folder indexador/index. The index folder is the only one in indexador which has no users with permissions. After setting permissions accordingly I can continue the Analysis. IPED is working with administrator permissions. Is there a way to change the way the index folder is beeing created by IPED?

Cheers!

**Comment by lfcnassif** [comment] 2021-08-13 14:19
Hi,
So this error doesn't happen with version 3.18.6 with the exact same environment, configuration and case? This is strange, because the last commit on Manager class (that creates and copies the index) was before 3.18.6 version. If you could share the processing log privately, it should help.

If you go to conf/AdvancedConfig.txt, there is an option called useNIOFSDirectory, enabling it can help when indexing to a network folder, but this depends on indexTempOnSSD option and if you are using --append. Again, the full log should help.

**Comment by CupOfCoke** [comment] 2021-08-17 08:26
Hi, first of all thank you for the quick response. Unfortunately I am not able to share the process log because of private data inside. However I was able to reproduce the error with a different image. Here are my options for indextemp and output:

`indexTemp = D:

indexTempOnSSD = true

outputOnSSD = false`

Looking at my temp partition/folder, I see lots of indexador-temp files, which should be correct I suppose. The only cmdline argument I am using is the --portable option. In the following Screenshot you can see, that again with the new image there are no user/permissions defined for this folder only.
![IPED](https://user-images.githubusercontent.com/88881399/129691170-59af72e7-5121-48b0-98d5-b780df95c03d.png)

**Comment by lfcnassif** [comment] 2021-08-17 13:17
I'm not sure if we will be able to help you with this without the log, you can send it privatelly to my email.

Could you confirm if this happens with 3.18.6 with the same configuration and environment?

Have you tried the suggested useNIOFSDirectory option?

Are you able to reproduce this pointing the output folder to a local disk instead of a samba share?

We don't set any kind of file or folder permission in the code, so maybe this is related with your environment setting...

**Comment by lfcnassif** [comment] 2021-08-17 16:32
I did some tests with -o pointing to a CIFS share, using v3.18.7 on Windows 10 (host) and the same options you posted here, I was not able to reproduce.

When indexTempOnSSD == true and without using --append, the index is created locally and copied to output at the end using the same general function used for the other folders.

**Comment by lfcnassif** [comment] 2021-08-23 19:12
Closing as "can't reproduce". If you can provide all asked info and a detailed step-by-step to reproduce this, please reopen.

**Closed by lfcnassif** 2021-08-23 19:12 UTC
Labels: need info, can't reproduce

**Comment by CupOfCoke** [comment] 2021-09-16 11:48
Sorry for the late response. I solved the problem by adding the Windows "Everyone" group permission with full rights to the Temp Folder/Partition. Thank you nevertheless for your efforts!
