### ISSUE TITLE
Error carving on

### ISSUE THREAD

**Issue by MariasStory** [sepinf-inc/IPED#1673] opened 2023-05-04 19:42 UTC
Want to report an error with image processing that I got while using the latest release binaries 4.1.2 05987a8
2023-05-02 17:23:49	[WARN]	[task.carver.CarverTask]			ParsingThread-28 Error carving on ... java.nio.channels.ClosedByInterruptException
java.nio.channels.ClosedByInterruptException
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(Unknown Source)
	at java.base/sun.nio.ch.FileChannelImpl.read(Unknown Source)
	at iped.utils.SeekableFileInputStream.read(SeekableFileInputStream.java:34)
	at java.base/java.io.BufferedInputStream.fill(Unknown Source)
	at java.base/java.io.BufferedInputStream.read1(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at iped.engine.task.carver.CarverTask.fillBuf(CarverTask.java:138)
	at iped.engine.task.carver.CarverTask.findSig(CarverTask.java:155)
	at iped.engine.task.carver.CarverTask.safeProcess(CarverTask.java:120)
	at iped.engine.task.carver.CarverTask.process(CarverTask.java:75)
        ...

**The version iped-snapshot-1ef9d59d7cd0e6f469cf6d7a594c81ea391ecbe3.zip worked on the image.**

Maybe it is time to update the release?

**Comment by lfcnassif** [comment] 2023-05-04 21:36
Has the processing aborted? If yes, above error wasn't the source, it just says processing threads were interrupted because another fatal error occurred. We would need the full stacktrace that follows the "Processing error" message in the log, or the full log privatelly would be even better.

**Comment by MariasStory** [comment] 2023-05-05 07:14
Yes, it did abort, even after running with "continue".
OK, it seems that I did not identify the source of the critical error.
I already deleted the logs, but there were alot and I can't share them.
Because of the fact that the newer (snapshot) version is working for me on the same image, I assume that the problem fixed any way.
We can close the issue.
The only problem, if someone else is trying to use the current release binaries and gets frustrated because the tool does not work.

**Comment by lfcnassif** [comment] 2023-05-05 12:46
No known aborting bugs were fixed since 4.1.2 release, neither in the branch waiting for review that worked for you. Maybe that was caused by something in your environment, maybe by some specific configuration into the tool.

Without additional information about the issue, to reproduce it and test a possible fix, there is nothing that could be done by us. Since the reported stacktrace is not an actual issue, I'm closing this as invalid.

**Closed by lfcnassif** 2023-05-05 12:46 UTC
Labels: need info
