### ISSUE TITLE
Getting Sleuthkit: Error: Cannot determine file system type (Sector offset: 0)

### ISSUE THREAD

**Issue by mcquadenc** [sepinf-inc/IPED#405] opened 2021-03-22 20:22 UTC
I am getting the following error when processing an evidence.

The principle was receiving this error from a container docker. However, I performed tests on the windows platform and got the same error.

I am using IPED version 3.18.4, but the evidence in question was indexed by IPED version 3.8 without the error occurring.
However, I can mount the image normally:

[+] Mounting image /BASE_DADOS/ITEM/Images/IMAGEM.E01 using auto ...
[+] Mounted raw image [1/1]
[+] Mounted volume 931.5 GiB 2: NTFS SAMSUNG [Windows XP] on / tmp / im_2_xxxxxx_SAMSUNG.
>>> Press [enter] to unmount the volume, or ^ C to keep mounted ...
[+] Parsed all volumes!
[+] Analysis complete, unmounting ...
[+] All cleaned up

The situation is that I am reindexing a dozen old pieces of evidence to build a single case of analysis.

Image E01 metadata:
 EWF/Expert Witness/EnCase image file format

Error Log (IPED 3.18.4):
```
2021-03-22 15:38:32	[MSG]	[indexer.process.ProgressConsole]			Configurando índice...
2021-03-22 15:38:36	[MSG]	[indexer.process.ProgressConsole]			Inicializando SkipCommitedTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando IgnoreHardLinkTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando TempFileTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando SignatureTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando SetTypeTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando SetCategoryTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando RefineCategoryTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando HashTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando KFFTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando LedKFFTask
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando ProjectVICHashLookup
2021-03-22 15:38:37	[MSG]	[indexer.process.ProgressConsole]			Inicializando DuplicateTask
2021-03-22 15:38:39	[MSG]	[indexer.process.ProgressConsole]			Inicializando AudioTranscriptTask
2021-03-22 15:38:39	[MSG]	[indexer.process.ProgressConsole]			Inicializando VideoThumbTask
2021-03-22 15:38:39	[MSG]	[indexer.process.ProgressConsole]			Inicializando ParsingTask
2021-03-22 15:38:39	[MSG]	[indexer.process.ProgressConsole]			Inicializando RegexTask
2021-03-22 15:38:41	[MSG]	[indexer.process.ProgressConsole]			Inicializando LanguageDetectTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando NamedEntityTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando ExportFileTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando MakePreviewTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando ImageThumbTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando DIETask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando ImageSimilarityTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando PhotoDNATask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando PhotoDNALookup
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando KFFCarveTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando CarverTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando KnownMetCarveTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando FragmentLargeBinaryTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando EntropyTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando ElasticSearchIndexTask
2021-03-22 15:38:42	[MSG]	[indexer.process.ProgressConsole]			Inicializando IndexTask
2021-03-22 15:38:48	[MSG]	[indexer.process.ProgressConsole]			Inicializando GraphTask
2021-03-22 15:38:49	[MSG]	[indexer.process.ProgressConsole]			Inicializando ExportCSVTask
2021-03-22 15:38:49	[MSG]	[indexer.process.ProgressConsole]			Inicializando HTMLReportTask
2021-03-22 15:39:14	[MSG]	[indexer.process.ProgressConsole]			Adicionando '/BASE_DADOS/ITEM/Imagens/IMAGEM.E01'
2021-03-22 15:39:15	[MSG]	[indexer.process.ProgressConsole]			Aguarde, decodificando imagem /BASE_DADOS/ITEM/Imagens/IMAGEM.E01
2021-03-22 15:39:19	[ERROR]	[indexer.datasource.SleuthkitReader$2]			Sleuthkit: Error: Cannot determine file system type (Sector offset: 0)
2021-03-22 15:39:20	[MSG]	[indexer.process.ProgressConsole]			Localizados 1 arquivos
2021-03-22 15:39:22	[MSG]	[indexer.process.ProgressConsole]			Processando 1/1 (0%) 0GB/h
2021-03-22 15:39:24	[MSG]	[indexer.process.ProgressConsole]			Processando 1/1 (0%) 0GB/h
2021-03-22 15:39:24	[MSG]	[indexer.process.ProgressConsole]			Saving extracted text sizes...
2021-03-22 15:39:25	[MSG]	[indexer.process.ProgressConsole]			Finishing graph CSVs...
2021-03-22 15:39:26	[MSG]	[indexer.process.ProgressConsole]			Generating graph database...
2021-03-22 15:39:43	[MSG]	[indexer.process.ProgressConsole]			Compressing graph CSVs...
2021-03-22 15:39:43	[MSG]	[indexer.process.ProgressConsole]			Fechando Índice...
2021-03-22 15:39:44	[MSG]	[indexer.process.ProgressConsole]			Filtrando palavras-chave...
2021-03-22 15:39:48	[MSG]	[indexer.process.ProgressConsole]			Finalizado

```
What to say about this error?

**Comment by lfcnassif** [comment] 2021-03-22 23:02
Could you test old IPED version 3.15.6? You can find it at old download site: https://servicos.dpf.gov.br/ferramentas/IPED/3.15.6/

And could you test last version (4.10.1) of tsk_loaddb tool? Yoy can find it at https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.10.1

It is used by IPED for file system decoding. We are using an old version, if it works, will increase the priority of #232

**Comment by mcquadenc** [comment] 2021-03-22 23:28
> Could you test old IPED version 3.15.6? You can find it at old download site: https://servicos.dpf.gov.br/ferramentas/IPED/3.15.6/
> 
> And could you test last version (4.10.1) of tsk_loaddb tool? Yoy can find it at https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.10.1
> 
> It is used by IPED for file system decoding. We are using an old version, if it works, will increase the priority of #232

Of course, tomorrow I will give you feedback on the results. Thanks.

**Comment by lfcnassif** [comment] 2021-03-25 02:24
The partial log you have posted seems to be from an old version (3.8?). Recent versions log messages are all in english. Are you sure some previous version decoded the E01 correctly?

**Comment by mcquadenc** [comment] 2021-03-30 20:49
> Could you test old IPED version 3.15.6? You can find it at old download site: https://servicos.dpf.gov.br/ferramentas/IPED/3.15.6/
> 
> And could you test last version (4.10.1) of tsk_loaddb tool? Yoy can find it at https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.10.1
> 
> It is used by IPED for file system decoding. We are using an old version, if it works, will increase the priority of #232

Hello @lfcnassif , I came to give feedback on this issue. 
I was able to configure the IPED 3.18.2 to 4.10.1 sleuthkit, but I had to do some modifications to debug the application.

However, I managed to make IPED able to recognize the partition system, despite the alerts presented.

```
[...]
2021-03-23 19:01:23	[MSG]	[indexer.process.ProgressConsole]			Inicializando GraphTask
2021-03-23 19:01:23	[MSG]	[indexer.process.ProgressConsole]			Inicializando ExportCSVTask
2021-03-23 19:01:23	[MSG]	[indexer.process.ProgressConsole]			Inicializando HTMLReportTask
2021-03-23 19:01:23	[ERROR]	[indexer.datasource.SleuthkitReader]			It is highly recommended to apply the iped patch (in sources folder) on sleuthkit!
2021-03-23 19:01:23	[ERROR]	[indexer.datasource.SleuthkitReader]			Sleuthkit version 4.10.1 not supported. Install version 4.6.5
2021-03-23 19:01:23	[MSG]	[indexer.process.ProgressConsole]			Adicionando '/BASE_DADOS/ITEM/Images/IMAGEM.E01'
2021-03-23 19:01:23	[MSG]	[indexer.process.ProgressConsole]			Criando /root/OUTUPUT/sleuth.db
2021-03-23 19:01:24	[MSG]	[indexer.process.ProgressConsole]			Aguarde, decodificando imagem /BASE_DADOS/ITEM/Images/IMAGEM.E01
2021-03-23 19:01:24	[ERROR]	[indexer.datasource.SleuthkitReader$2]			Sleuthkit: Error: Cannot determine file system type (Sector offset: 64, Partition Type: NTFS / exFAT (0x07))
2021-03-23 19:01:25	[MSG]	[indexer.process.ProgressConsole]			Localizados 948 arquivos Termino em 2447h 41m 49s
2021-03-23 19:01:26	[MSG]	[indexer.process.ProgressConsole]			Processando 6/969 (0%) 0GB/h Termino em 2724h 58m 22s
2021-03-23 19:01:27	[MSG]	[indexer.process.ProgressConsole]			Processando 27/1006 (0%) 0GB/h Termino em 3003h 4m 56s
2021-03-23 19:01:28	[MSG]	[indexer.process.ProgressConsole]			Processando 63/1050 (0%) 0GB/h Termino em 3280h 54m 50s
2021-03-23 19:01:29	[MSG]	[indexer.process.ProgressConsole]			Processando 108/1086 (0%) 0GB/h Termino em 3558h 44m 44s
2021-03-23 19:01:30	[MSG]	[indexer.process.ProgressConsole]			Processando 144/1115 (0%) 0GB/h Termino em 3836h 34m 38s
2021-03-23 19:01:31	[MSG]	[indexer.process.ProgressConsole]			Processando 173/1136 (0%) 0GB/h Termino em 4114h 41m 13s
[...]
2021-03-23 19:07:13	[MSG]	[indexer.process.ProgressConsole]			Processando 100117/100168 (100%) 9393GB/h Termino em 0h 0m 0s
2021-03-23 19:07:14	[MSG]	[indexer.process.ProgressConsole]			Processando 100168/100168 (100%) 9367GB/h Termino em 0h 0m 0s
2021-03-23 19:07:16	[MSG]	[indexer.process.ProgressConsole]			Processando 100168/100168 (100%) 9315GB/h Termino em 0h 0m 0s
2021-03-23 19:07:17	[MSG]	[indexer.process.ProgressConsole]			Processando 100168/100168 (100%) 9289GB/h Termino em 0h 0m 0s
2021-03-23 19:07:17	[MSG]	[indexer.process.ProgressConsole]			Saving extracted text sizes...
2021-03-23 19:07:17	[MSG]	[indexer.process.ProgressConsole]			Fechando Índice...
2021-03-23 19:07:20	[MSG]	[indexer.process.ProgressConsole]			Copiando Índice...
2021-03-23 19:07:20	[MSG]	[indexer.process.ProgressConsole]			Filtrando palavras-chave...
2021-03-23 19:07:20	[ERROR]	[indexer.process.Statistics]			Alert: Errors while reading 95730 items! Maybe the datasource was unavailable!
2021-03-23 19:07:20	[MSG]	[indexer.process.ProgressConsole]			Finalizado
```

But, in the iped logs mentioned in this post, it is possible to check the following alert, that in fact the files were not identified in the indexing, but only binary files without readable content:
`Alert: Errors while reading 95730 items! Maybe the datasource was unavailable!`

tsk_loaddb (4.10.1 sleuthkit)
```
tsk_loaddb  /BASE_DADOS/ITEM/Images/IMAGEM.E01
Error: Cannot determine file system type (Sector offset: 64, Partition Type: NTFS / exFAT (0x07))
Database stored at: /root/IMAGEM.E01.db
```

IMAGEM.E01.db content: 
```
sqlite> SELECT * FROM data_source_info;
1|||Notes: 000000000XXXXXXX
Model: Samsung M3 Portable
Serial Number: 000000000XXXXXXX
Acquired Date: Fri Feb XX XX:XX:XX XXXX
System Date: Fri Feb XX XX:XX:XX XXXX
Acquiry Operating System: Linux deft 3.0.0-12-generic #20-Ubuntu SMP Fri Oct 7 xx:xx:xx UTC 20xx i686
Acquiry Software Version: guymager 0.6.5-1
```

I say that I was not successful with the latest version, as suggested.

As you had suggested, I tested version 3.15.6 and it worked perfectly to perform the indexing, but unfortunately I can't do the `append` for the case processed by version 3.18.2.
I also noticed that there is a difference between the versions:
IPED 3.15.6: Possui sleuthkit-4.6.0-p01.jar
IPED 3.18.2: Possui sleuthkit-4.6.5-p05.jar

I believe that this may be the problem. I will test IPED 3.18.2 with this specific version of sleuthkit-4.6.0-p01.

**Comment by mcquadenc** [comment] 2021-03-30 21:13
> The partial log you have posted seems to be from an old version (3.8?). Recent versions log messages are all in english. Are you sure some previous version decoded the E01 correctly?

I fixed  the indication of the version of the log, it is version 3.18.4. That didn't work.
 
The IPED that had processed perfectly this evidence was the following: Digital Evidence Indexer and Processor 3.8.1. In this version there is only a parser alert.

But I also tested version 3.15.6 and it worked perfectly as I explained earlier.

**Comment by lfcnassif** [comment] 2021-03-30 23:35
Thank you for the feedback. IPED versions > 3.16 uses a sleuthkit-4.6.5 fork with a huge patch for APFS support implemented by BlackBag (sleuthkit delayed more than 1.5 year to integrate it). So we applied the patch by ourselves and added some java-jni support. Months later, sleuthkit integrated APFS support. But we didn't upgraded yet, see #232.

I see that your test with IPED+sleuthkit-4.10.1 (and standalone tsk_loaddb-4.10.1) printed a decoding error:
Error: Cannot determine file system type (Sector offset: 64, Partition Type: NTFS / exFAT (0x07))

That means a whole partition (and its files) was not recognized.

IPED-3.18.2 also was not able to read the content of 95730 files using sleuthkit-4.10.1, this is a bad error. You can identify those files using "Read Error" filter in the analysis app. Try to extract the content of some of those files using official icat tool (from sleuthkit-4.10.1), if you can't, that means sleuthkit-4.10.1 is still with problems.

If IPED-3.15.6 (before APFS patch) has none of above errors, that is another tip that official sleuthkit-4.10.1 has some bug possibly related with APFS integration. You will need to report your errors with standalone sleuthkit-4.10.1 (tsk_loaddb and icat tools) directly to their project, as only you can provide details about your image and the output of some commands that they will possibly ask.

**Comment by lfcnassif** [comment] 2021-03-30 23:43
Another test is to do SELECT * FROM tsk_files; on the sqlite databases created by tsk_loaddb versions 4.6.5 and 4.10.1. If the number of returned results differ, that is another tip of a regression with recent sleuthkit versions.

**Comment by lfcnassif** [comment] 2021-04-06 01:34
I'm closing this as 'won't fix' because without an image to reproduce, we can't do anything, sorry.

I ask you to report this directly to sleuthkit project, you can reference this issue, and provide them the verbose output of mmls, fsstat, icat (on files with read errors) and tsk_loaddb tools of the versions that worked and didn't (4.6.5 and 4.10.1), possibly they will ask you more details about your image.

If you have answers to the asked questions, you can post them here, but I think this will need to be fixed in sleuthkit project anyway.

**Closed by lfcnassif** 2021-04-06 01:34 UTC
Labels: bug

**Comment by lfcnassif** [comment] 2021-04-14 22:27
Just a tip here, when sleuthkit fails to recognize the volume system or file system, a workaround is to convert the DD/E01 image file to an AD1 logical image using FTKImager and process the AD1 with IPED. IPED decodes AD1 images directly, without using sleuthkit, so it works. It is also possible to include unallocated areas into the AD1, so you will be able to recover deleted files too.

**Comment by paulobreim** [comment] 2022-04-09 14:57
I cloned a notebook with a 250GB ssd nvme with dd_rescue
When I went to index I got this error.

2022-04-08 22:44:41     [ERROR] [indexer.datasource.SleuthkitReader$2]                  Sleuthkit error processing d:\evidence\evidence.dd: Error: Cannot determine file system type (Sector offset: 571392, Partition Type: Basic data partition)

I tested with IPED
3.18.12, 3.18.14 and 3.15.6 and got the same error

Using FTKImager version 4.7.1.2  with the option Add Evidence Item, the partition with the windows show the message:
Unrecognized file system [Data]

I tried to generate an AD1 image which took 2:14 and when examining the image it continued to be unrecognized and considered it an unallocated area file when use the option Add Evidence

Interestingly, using the option to mount image from .dd it mounted correctly.
I'm going to index from this mounted image but I still don't know if this image includes deleted files, carving, etc.

**Comment by lfcnassif** [comment] 2022-04-09 23:17
Hi @paulobreim. If FTKImager didn't recognize the FS, but, after mounting it, Windows did, maybe the disk is encrypted with BitLocker, but the encryption key was opened. This often happens when user disables BitLocker, instead of decrypting the whole disk, Windows simply makes the encryption key open. Check the FS data into FTKImager, if it looks random, maybe this is the case. I would make another DD/E01 image from the mounted drive letter and later process the decrypted image.

If that is not the case, you can try this IPED snapshot **alpha** version, we are upgrading Sleuthkit version, currenlty version 4.11.0 is being used in this branch: https://github.com/sepinf-inc/IPED/actions/runs/2104786688

A last try would be to run latest tsk_loaddb tool from Sleuthkit-4.11.1, seems they fixed some issues with NTFS decoding: https://github.com/sleuthkit/sleuthkit/releases

**Comment by paulobreim** [comment] 2022-04-10 01:02
See what a curious situation
1 - I mounted the SSD image (4 partitions) with FTKImager.
2 - He assigned the letter L: to the partition that has windows.
3 - I ran iped to index the L drive:
4 - I unmounted and closed FTK.
5 - I ran the IPED-SearchApp.exe
6 - As expected, when I go to open a file, it complains that it didn't find the L: drive and when it asks for the path, I provided the original dd image and it opens the file normally.

Checking the explorer, we can see a yellow exclamation mark, which indicates that it has BItLoker, showing that it is exactly the situation you described.
To confirm, I tried mounting the image with OSFMount, which failed to mount.

![Screenshot_20220409_215048](https://user-images.githubusercontent.com/381594/162596571-5061e5ab-cee8-415b-ba68-01e00333f101.png)

So, if IPED is able to read the files directly from the DD, it means that it managed to mount the partition that has Bitlocker.
What's the explanation for that?

Finally, when testing with version 4.11 I get the message¨

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: dpf/sp/gpinf/indexer/Main has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by lfcnassif** [comment] 2022-04-10 02:28
I think Sleuthkit is not able to read a Bitlocker encrypted FS, then IPED is not able too. Even pointing to an incorrect volume, IPED is able to open container subitems, because they are stored in case folder. Try to apply "Actual Files" filter, it will list only files directly allocated in FS and I think they won't be accessible if the original volume isn't mounted or if you point to an incorrect one.

About the last error, iped-4.0 needs java 11. Try to use iped.exe, it will use the new embedded java 11 runtime.

**Comment by paulobreim** [comment] 2022-04-11 00:21
I tested it with iped.exe, but as expected it doesn't work around the bitlocker issue either.
I was curious because if windows allows turning off bitlocker, but the hd remains encrypted, somewhere the bitlocker key has to be stored for FTK to be able to mount and access it. It makes no sense to turn off bitlocker.

Regarding the filter, "Actual Files" what is the equivalent in Portuguese?

![Screenshot_20220410_210649](https://user-images.githubusercontent.com/381594/162645979-65524a43-027a-4ca0-8972-4cd12e5a3dfe.png)

tks

**Comment by paulobreim** [comment] 2022-04-11 16:22
understood.
you are right in what you put.
I think the best option for this case is to generate a dd image from the hd mounted by ftk

tks
