### ISSUE TITLE
Processing frozen

### ISSUE THREAD

**Issue by fcscoutinho** [sepinf-inc/IPED#324] opened 2020-11-22 19:37 UTC
Estou fazendo o processamento de evidências e após um tempo o IPED fica parado...
Verifiquei o LOG e ele está fazendo alguns commits.
Isso é normal? (Ainda faltam alguns itens para a finalização, mas os processadores ficam com status "Aguardando item..."
[IPED-2020-11-22-09-55-17.log](https://github.com/sepinf-inc/IPED/files/5580168/IPED-2020-11-22-09-55-17.log)
![IPED](https://user-images.githubusercontent.com/38664286/99915201-0189bd80-2ce1-11eb-8ec5-61923e89f0d0.png)

**Comment by fcscoutinho** [comment] 2020-11-23 00:02
Estou gerando imagem iso com cdBurnerXP e sistemas de arquivos UDF. Existe algum tip de incompatibilidade com IPED (tenho caixas de e-mail maiores que 4gb)

**Comment by lfcnassif** [comment] 2020-11-23 14:59
This is a Sleuthkit-4.6.5 issue, it didn't finish to decode your ISO file (tsk_loaddb process should be still running, there is no message about it finishing in log), so total item count is unknown and IPED cannot estimate time to finish nor provide the processing progress.

Please try latest tsk_loaddb version to check if they fixed it: https://github.com/sleuthkit/sleuthkit/releases/tag/sleuthkit-4.10.1

Instead of generating ISO9660 mixed with UDF, you coud try UDF only ISO, so 7zip will be used to decode the image (TSK does not support ISO96660 but 7zip does). Other option is creating an AD1 container, IPED decodes it without using TSK, or VHD/VMDK virtual disks (decoded using TSK).

AFAIK, IPED have no problem wth large mailboxes, we have processed mailboxes larger than 10GB.

PS: Please write in english, other users from other countries could have the same issue.

**Comment by fcscoutinho** [comment] 2020-11-23 15:26
Thank you Nassif!

**Comment by lfcnassif** [comment] 2020-11-23 22:59
Please, if you are going to try some of the suggested approaches, report back, thanks.

**Comment by fcscoutinho** [comment] 2020-11-23 23:37
I finished indexing without completing the process and generated an image of the files of the telematic data break by FTK (AD1) and started indexing again. I'll let you know as soon as I finish the process (it's 300Gb to index) ...

**Comment by lfcnassif** [comment] 2020-11-24 03:19
If it has shown progress or has estimated time to finish, the above issue has gone.

**Comment by fcscoutinho** [comment] 2020-11-24 10:30
Apparently all right !!!!

![IPED_2](https://user-images.githubusercontent.com/38664286/100082301-d7421800-2e26-11eb-91c8-e998c2e31b08.png)

**Comment by fcscoutinho** [comment] 2020-11-24 10:32
I downloaded the latest changes from IPED, compiled it and it looks like it worked!

**Comment by fcscoutinho** [comment] 2020-11-24 10:33
We are using IPED here at MPGO very successfully. Thank you Nassif.

**Comment by lfcnassif** [comment] 2020-11-24 13:30
Ok I will close the issue. Please run the tsk_loaddb tool on your ISO image and report the original problem on sleuthkit project if it persists. We cannot report there as we can't reproduce or provide details about your image.

**Closed by lfcnassif** 2020-11-24 13:30 UTC
