### ISSUE TITLE
Whatsapp Forwarded messages

### ISSUE THREAD

**Issue by gfd2020** [sepinf-inc/IPED#1287] opened 2022-08-24 18:22 UTC
Suggestion
Include in whatsapp chat messages the indication if the message has been forwarded.

How
The flag of this behavior are indicated as below (unless I'm mistaken. In my tests, it seems correct.)

IPHONE
ZWAMESSAGE.ZFLAGS bit 7
Example and test: select (1 << 7 & ZFLAGS) as forwarded from ZWAMESSAGE

ANDROID NEW
message.origination_flags bit 1
Example and test: select (origination_flags & 1) as forwarded FROM message

ANDROID OLD
messages.forwarded bit 1
Example and test: select (forwarded & 1) as forwarded FROM messages

On the ReportGenerator.java, add something like this ...

if (message.getForwarded() > 0) {
	out.println("<span><img src=\"" + RSRC_PATH + "img/forward.png\" valign=\"top\"/><i style=\"color:gray\">Forwarded</i></span></br>");
}

**Comment by lfcnassif** [comment] 2022-08-24 18:48
Thanks @gfd2020, this can be very useful.

**Comment by filipesimoes** [comment] 2023-05-10 19:41
Hello.
This is important. It may cause a lot of confusion during the analysis of Whatsapp.

**Comment by lfcnassif** [comment] 2023-05-10 19:49
I started a regression test yesterday on hundreds of whatsapp databases using PR #1651 and if everything looks good, I'll merge it. I noticed rendering lags when viewing large WhatsApp chats with that PR, I still need to check on master to confirm if it is a performance regression or not. Do you noticed something similar @tc-wleite?

**Comment by tc-wleite** [comment] 2023-05-10 20:02
> I started a regression test yesterday on hundreds of whatsapp databases using PR #1651 and if everything looks good, I'll merge it. I noticed rendering lags when viewing large WhatsApp chats with that PR, I still need to check on master to confirm if it is a performance regression or not. Have you noticed something similar @tc-wleite?

Large chats (the ones that are broken into parts) do cause rendering lags. But it doesn't seem to be something critical, at least in the cases that I tested here. It seems to be the same kind of lag present when opening larger HTMLs in the internal viewer.
I didn't observe any noticeable difference in that sense, comparing to master.

Not sure if it is the same type of delay you are observing. You can send me a sample database if you see larger lags than we had before, so I can investigate in more detail.

**Comment by gfd2020** [comment] 2023-05-10 21:57
Is the htmlviewer using javafx? 
May be this could help ...
https://docs.oracle.com/javafx/2/ui_controls/pagination.htm
I make a small demo and works. We just need to split the chat in pages ...

**Comment by lfcnassif** [comment] 2023-05-10 22:28
> We just need to split the chat in pages ...

This is already done explicitly for large chats, users can see many chat items referring to the same conversation. Maybe the max chat chunk size could be decreased, currently it is ~5MiB, but splitting too much can be annoying to users. Other approach could be splitting based on the number of messages, not on chat html size, actually it was done in the past and I don't know what is heavier to be rendered (5 MiB of text messages or 5MiB of multimedia messages).

**Comment by tc-wleite** [comment] 2023-05-10 22:30
> Is the htmlviewer using javafx? May be this could help ... https://docs.oracle.com/javafx/2/ui_controls/pagination.htm I make a small demo and works. We just need to split the chat in pages ...

Large chats are already split into parts (different items). It doesn't use a pagination like this one, but I am not sure if this is really necessary. Simply reducing a bit the chat split threshold would help, but it is probably better to understand first if it is a regression or something else happening in particular chats, as I didn't observe any critical delay.

**Comment by lfcnassif** [comment] 2023-05-10 22:51
Hi @tc-wleite, I got more parsing exception with #1651 than master. After I confirm them, I'll send the triggering samples privately to you.

**Comment by lfcnassif** [comment] 2023-05-10 22:56
PS: Thanks for helping with this!

**Comment by lfcnassif** [comment] 2023-05-11 01:58
> Hi @tc-wleite, I got more parsing exceptions with #1651 than master. After I confirm them, I'll send the triggering samples privately to you.

I confirmed 4 NPEs, 3 of them with this stacktrace for sure:
```
org.apache.tika.exception.TikaException: WAExtractorException Exception
	at iped.parsers.whatsapp.WhatsAppParser.parseWhatsappMessages(WhatsAppParser.java:377)
	at iped.parsers.whatsapp.WhatsAppParser.parse(WhatsAppParser.java:252)
	at org.apache.tika.parser.CompositeParser.parse(CompositeParser.java:298)
	at iped.parsers.standard.StandardParser.parse(StandardParser.java:245)
	at iped.engine.io.ParsingReader$BackgroundParsing.run(ParsingReader.java:247)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
	at iped.parsers.whatsapp.ExtractorIOS.decodeReceiptInfo(ExtractorIOS.java:484)
	at iped.parsers.whatsapp.ExtractorIOS.createMessageFromDB(ExtractorIOS.java:377)
	at iped.parsers.whatsapp.ExtractorIOS.extractMessages(ExtractorIOS.java:269)
	at iped.parsers.whatsapp.ExtractorIOS.extractChatList(ExtractorIOS.java:198)
	at iped.parsers.whatsapp.Extractor.getChatList(Extractor.java:34)
	at iped.parsers.whatsapp.WhatsAppParser.parseWhatsappMessages(WhatsAppParser.java:369)
```
I just sent the triggering samples to you by Teams.

**Comment by tc-wleite** [comment] 2023-05-11 02:24
Thanks! 
I will look into this tomorrow.

**Comment by patrickdalla** [comment] 2023-05-11 11:09
We could improve some of this 'lag' implementing some lazy loading logic via 'javascript'. This could be done transparently via in HTMLViewer, so if it is a good idea, we can create new specific issue.

**Comment by tc-wleite** [comment] 2023-05-11 12:15
> We could improve some of this 'lag' implementing some lazy loading logic via 'javascript'. This could be done transparently via in HTMLViewer, so if it is a good idea, we can create new specific issue.

I tested this again this morning, and didn't find any critical lag (obviously the "critical" threshold is kind of personal), neither observed any difference comparing to previous (master and 4.1.x) versions.
So unless @lfcnassif has any specific case that triggers a regression or a problematic delay, I wouldn't change the current behavior.

**Comment by lfcnassif** [comment] 2023-05-11 19:52
> I tested this again this morning, and didn't find any critical lag (obviously the "critical" threshold is kind of personal), neither observed any difference comparing to previous (master and 4.1.x) versions.
> So unless @lfcnassif has any specific case that triggers a regression or a problematic delay, I wouldn't change the current behavior.

Hi @tc-wleite, I took a closer look, there is no regression, sorry. The lag issue is with a specific database with a specific chat with a corrupted text message which is a few MBs of size, that message causes the slow rendering both on #1651 and on master, so that's an unrelated issue.

By the way, I'm getting a different number of messages within different runs caused by an unrelated issue, that is making comparisons harder. I'll describe it in another ticket.

**Comment by tc-wleite** [comment] 2023-05-11 19:54
> > Hi @tc-wleite, I got more parsing exceptions with #1651 than master. After I confirm them, I'll send the triggering samples privately to you.
> 
> I confirmed 4 NPEs, 3 of them with this stacktrace for sure:

I pushed a fix this morning that seems to fix this issue.

**Comment by lfcnassif** [comment] 2023-05-11 20:08
> I pushed a fix this morning that seems to fix this issue.

I saw it, thank you!

**Closed** 2023-05-12 00:59 UTC
Labels: enhancement
