### ISSUE TITLE
Some compression methods are not uncompressed when 7z is generated natively by Windows.

### ISSUE THREAD

**Issue by gfd2020** [sepinf-inc/IPED#2328] opened 2024-10-02 00:29 UTC
Windows gained a native compression option with 7z (make new archive). This way, you can choose the compression method. Some methods do not work when processed in IPED (tested version 4.1.6). 
See details below:

win-bzip2 - do not work
win-deflate - do not work
win-lzma1 - do not work
win-ppmd - do not work
win-lzma2 - works
win-store - works

I also tested compressing with original 7z:

7z-bzip2 - works
7z-lzma - works
7z-lzma2 - works
7z-ppmd - do not work ( only folders)

**Comment by lfcnassif** [comment] 2024-10-02 01:31
This windows feature is new for me... not supporting win-deflate is surprising, since it should be the default zip algorithm, maybe some additional headers were added...

**Comment by gfd2020** [comment] 2024-10-07 17:53
@lfcnassif , I did more tests. In the master version, the files are decompressed correctly. I just can't say why. I believe that this update, which is in master, could be included in version 4.2.

In master:

win-bzip2 - works
win-deflate - works
win-lzma1 - works
win-ppmd - do not work
win-lzma2 - works
win-store - works

**Comment by lfcnassif** [comment] 2024-10-08 00:55
> @lfcnassif , I did more tests. In the master version, the files are decompressed correctly. I just can't say why. I believe that this update, which is in master, could be included in version 4.2.

Thank you @gfd2020 for your tests!

So could we close this as duplicate of #1961?

**Comment by gfd2020** [comment] 2024-10-08 01:01
> > @lfcnassif , I did more tests. In the master version, the files are decompressed correctly. I just can't say why. I believe that this update, which is in master, could be included in version 4.2.
> 
> Thank you @gfd2020 for your tests!
> 
> So could we close this as duplicate of #1961?

I think so ...

**Closed** 2024-10-08 01:04 UTC
Labels: duplicate, enhancement
